-- MERGE1 — gov_merge_property_apply: FOLD on collision instead of destroying the child row.
--
-- gov has run ZERO merges (gov_property_merge_backup is empty), but measured against the real unique
-- constraints, EVERY pair in v_gov_property_duplicate_review (397 groups) would collide:
--   investment_scores.property_id      UNIQUE(property_id) alone      -> 397/397 groups, 400 rows
--   property_embeddings.property_id    PK(property_id)                -> 334 groups, 336 rows
--   property_financials.property_id    UNIQUE(property_id,fiscal_year)-> 316 groups, 585 rows
--
-- The generic properties-FK loop's `WHEN unique_violation` arm ran an explicit
-- `DELETE FROM %s WHERE %I = $1` on the drop-side row(s). That is the SAME class as dia's cascade
-- loss, one step more direct: here the merge function itself deletes the content instead of relying
-- on a cascade to do it. Same fix shape as dia (see the sibling dialysis migration): a per-table
-- POLICY (re_derivable / fold_fill_blanks) is consulted before anything is discarded, and a fold
-- fills every NULL keep-side column from the drop row before the drop row is deleted.
--
-- Discipline: additive, reversible (re-create the prior function body), no data mutated -- gov has
-- run no merges and this migration merges none either. Historical count: docs/audits/
-- MERGE1_PROPERTY_MERGE_COLLISION_FOLD.md.

CREATE TABLE IF NOT EXISTS public.gov_merge_child_policy (
  table_name      text PRIMARY KEY,
  policy          text NOT NULL CHECK (policy IN ('re_derivable','fold_fill_blanks','resolve_status')),
  pk_col          text NOT NULL,
  conflict_cols   text[] NOT NULL DEFAULT '{}',
  resolve_column  text,
  resolve_value   text,
  notes           text,
  created_at      timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.gov_merge_child_policy IS
  'MERGE1: per-table fold policy consulted by gov_merge_fold_table() on a properties-FK repoint '
  'collision inside gov_merge_property_apply(). A table with no row here defaults to fold_fill_blanks '
  'off its own single-column PK -- never the old blind DELETE.';

INSERT INTO public.gov_merge_child_policy (table_name, policy, pk_col, conflict_cols, notes) VALUES
  ('investment_scores', 're_derivable', 'score_id', ARRAY['property_id'],
   'Every column is computed from properties/leases/loans/etc by investment_scorer.py -- no '
   'independent history (checked: no separate score-history table reads it). The drop-side row is '
   'discarded as RE-DERIVABLE, not counted as a loss; the next scoring pass recomputes it for keep_id.'),
  ('property_embeddings', 're_derivable', 'property_id', ARRAY['property_id'],
   'Embedding is derived from the property''s own text and is regenerated by the embedding refresh '
   'worker. Discarded as RE-DERIVABLE, not counted as a loss.'),
  ('property_financials', 'fold_fill_blanks', 'financial_id', ARRAY['property_id','fiscal_year'],
   'Substantive annual rent/expense/NOI history (~111K rows, CLAUDE.md financial tables). A collision '
   'means the SAME (property,fiscal_year) was recorded from both sides -- fold fills any blank on the '
   'keep row from the drop row rather than destroying either observation.')
ON CONFLICT (table_name) DO NOTHING;

CREATE OR REPLACE FUNCTION public._gov_merge_fold_one_row(
  p_table text, p_fk_col text, p_pk_col text, p_conflict_cols text[],
  p_keep_id integer, p_drop_pk text
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_keep_pk text;
  v_where_parts text[] := ARRAY[]::text[];
  v_col text;
  v_set_parts text[] := ARRAY[]::text[];
  v_n_cols int;
BEGIN
  -- The keep-side row is identified by its FK column equalling keep_id (NOT by its own PK, which
  -- may be an unrelated surrogate id -- e.g. property_financials.financial_id vs property_id) plus
  -- every other conflict-key column matching the drop row.
  v_where_parts := ARRAY[format('k.%I = $1', p_fk_col)];
  FOREACH v_col IN ARRAY p_conflict_cols LOOP
    IF v_col <> p_fk_col THEN
      v_where_parts := v_where_parts || format('k.%I IS NOT DISTINCT FROM d.%I', v_col, v_col);
    END IF;
  END LOOP;

  EXECUTE format(
    'SELECT k.%I::text FROM public.%I k JOIN public.%I d ON %s WHERE d.%I::text = $2',
    p_pk_col, p_table, p_table, array_to_string(v_where_parts, ' AND '), p_pk_col
  ) INTO v_keep_pk USING p_keep_id, p_drop_pk;

  IF v_keep_pk IS NULL THEN
    RETURN jsonb_build_object('fold', 'no_matching_keep_row_found', 'drop_pk', p_drop_pk);
  END IF;

  FOR v_col IN
    SELECT column_name FROM information_schema.columns
     WHERE table_schema = 'public' AND table_name = p_table
       AND column_name NOT IN (p_pk_col, p_fk_col)
       AND column_name <> ALL(p_conflict_cols)
  LOOP
    v_set_parts := v_set_parts || format('%I = COALESCE(k.%I, d.%I)', v_col, v_col, v_col);
  END LOOP;
  v_n_cols := COALESCE(array_length(v_set_parts,1), 0);

  IF v_n_cols > 0 THEN
    EXECUTE format(
      'UPDATE public.%I k SET %s FROM public.%I d WHERE k.%I::text = $1 AND d.%I::text = $2',
      p_table, array_to_string(v_set_parts, ', '), p_table, p_pk_col, p_pk_col
    ) USING v_keep_pk, p_drop_pk;
  END IF;

  EXECUTE format('DELETE FROM public.%I WHERE %I::text = $1', p_table, p_pk_col) USING p_drop_pk;

  RETURN jsonb_build_object('fold', 'filled_blanks', 'keep_pk', v_keep_pk, 'drop_pk', p_drop_pk,
    'columns_considered', v_n_cols);
END;
$function$;

CREATE OR REPLACE FUNCTION public.gov_merge_fold_table(
  p_table text, p_fk_col text, p_keep_id integer, p_drop_id integer
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_policy text; v_pk_col text; v_conflict_cols text[];
  v_resolve_column text; v_resolve_value text;
  v_row record; v_fold_detail jsonb;
  v_repointed int := 0; v_folded int := 0; v_discarded int := 0; v_resolved int := 0;
BEGIN
  SELECT policy, pk_col, conflict_cols, resolve_column, resolve_value
    INTO v_policy, v_pk_col, v_conflict_cols, v_resolve_column, v_resolve_value
  FROM public.gov_merge_child_policy WHERE table_name = p_table;

  IF v_policy IS NULL THEN
    SELECT CASE WHEN count(*) = 1 THEN max(a.attname) ELSE NULL END INTO v_pk_col
    FROM pg_index i JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = ANY(i.indkey)
    WHERE i.indrelid = format('public.%I', p_table)::regclass AND i.indisprimary;
    IF v_pk_col IS NULL THEN
      RETURN jsonb_build_object('policy', 'unclassified_no_single_col_pk', 'held', true,
        'note', 'no gov_merge_child_policy row and no single-column PK -- left pointing at drop_id, '
                 'will NOT be auto-deleted by this function; register a policy row before merging this pair');
    END IF;
    v_policy := 'fold_fill_blanks';
    v_conflict_cols := ARRAY[p_fk_col];
  END IF;

  FOR v_row IN EXECUTE format('SELECT %I::text AS pk FROM public.%I WHERE %I = $1', v_pk_col, p_table, p_fk_col)
               USING p_drop_id
  LOOP
    BEGIN
      EXECUTE format('UPDATE public.%I SET %I = $1 WHERE %I::text = $2', p_table, p_fk_col, v_pk_col)
        USING p_keep_id, v_row.pk;
      v_repointed := v_repointed + 1;
    EXCEPTION WHEN unique_violation THEN
      IF v_policy = 'resolve_status' AND v_resolve_column IS NOT NULL THEN
        BEGIN
          EXECUTE format('UPDATE public.%I SET %I = $1 WHERE %I::text = $2', p_table, v_resolve_column, v_pk_col)
            USING v_resolve_value, v_row.pk;
          EXECUTE format('UPDATE public.%I SET %I = $1 WHERE %I::text = $2', p_table, p_fk_col, v_pk_col)
            USING p_keep_id, v_row.pk;
          v_resolved := v_resolved + 1;
        EXCEPTION WHEN unique_violation THEN
          v_fold_detail := public._gov_merge_fold_one_row(p_table, p_fk_col, v_pk_col, v_conflict_cols, p_keep_id, v_row.pk);
          v_folded := v_folded + 1;
        END;
      ELSIF v_policy = 're_derivable' THEN
        EXECUTE format('DELETE FROM public.%I WHERE %I::text = $1', p_table, v_pk_col) USING v_row.pk;
        v_discarded := v_discarded + 1;
      ELSE
        v_fold_detail := public._gov_merge_fold_one_row(p_table, p_fk_col, v_pk_col, v_conflict_cols, p_keep_id, v_row.pk);
        v_folded := v_folded + 1;
      END IF;
    END;
  END LOOP;

  RETURN jsonb_build_object('policy', v_policy, 'repointed', v_repointed, 'folded', v_folded,
    'discarded_re_derivable', v_discarded, 'resolved_in_place', v_resolved);
END;
$function$;

-- gov_merge_property_apply: the properties-FK loop's unique_violation arm now folds instead of
-- deleting outright. Everything else (sales_transactions dedup, the final property DELETE) unchanged.
CREATE OR REPLACE FUNCTION public.gov_merge_property_apply(p_keep_id integer, p_drop_id integer)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions', 'pg_temp'
AS $function$
DECLARE
  v_rewired jsonb := '{}'::jsonb; v_count int; v_n int; v_table_name text;
  v_sid uuid; v_keep_sale uuid; v_fk record;
  v_rep int := 0; v_drp int := 0; v_setnull int := 0; v_children_repointed int := 0;
  v_fold_detail jsonb;
BEGIN
  IF p_keep_id = p_drop_id THEN RAISE EXCEPTION 'keep_id and drop_id must differ'; END IF;
  FOR v_sid IN SELECT sale_id FROM public.sales_transactions WHERE property_id = p_drop_id LOOP
    BEGIN
      UPDATE public.sales_transactions SET property_id = p_keep_id WHERE sale_id = v_sid;
      v_rep := v_rep + 1;
    EXCEPTION WHEN unique_violation THEN
      BEGIN
        SELECT k.sale_id INTO v_keep_sale FROM public.sales_transactions d
          JOIN public.sales_transactions k ON k.property_id = p_keep_id
           AND k.sale_date IS NOT DISTINCT FROM d.sale_date
           AND COALESCE(k.sold_price, -1) = COALESCE(d.sold_price, -1)
         WHERE d.sale_id = v_sid ORDER BY k.sale_id LIMIT 1;
        IF v_keep_sale IS NOT NULL THEN
          FOR v_fk IN SELECT t.relname AS tbl, a.attname AS col FROM pg_constraint c
              JOIN pg_class t ON t.oid=c.conrelid JOIN pg_namespace n ON n.oid=t.relnamespace
              JOIN pg_attribute a ON a.attrelid=c.conrelid AND a.attnum=ANY(c.conkey)
             WHERE c.contype='f' AND c.confrelid='public.sales_transactions'::regclass AND n.nspname='public'
          LOOP
            BEGIN
              EXECUTE format('UPDATE public.%I SET %I = $1 WHERE %I = $2', v_fk.tbl, v_fk.col, v_fk.col) USING v_keep_sale, v_sid;
              GET DIAGNOSTICS v_n = ROW_COUNT; v_children_repointed := v_children_repointed + v_n;
            EXCEPTION WHEN OTHERS THEN NULL; END;
          END LOOP;
        END IF;
        DELETE FROM public.sales_transactions WHERE sale_id = v_sid;
        v_drp := v_drp + 1;
        IF v_keep_sale IS NULL THEN v_setnull := v_setnull + 1; END IF;
      EXCEPTION WHEN OTHERS THEN
        v_rewired := v_rewired || jsonb_build_object('sales_transactions.sale_id_delete_failed:' || v_sid::text, SQLERRM);
      END;
      v_keep_sale := NULL;
    END;
  END LOOP;
  IF (v_rep + v_drp) > 0 THEN
    v_rewired := v_rewired || jsonb_build_object('sales_repointed', v_rep, 'sales_dedup_dropped', v_drp,
      'sale_children_repointed', v_children_repointed, 'sales_dropped_children_setnull', v_setnull);
  END IF;
  FOR v_table_name IN SELECT n.nspname || '.' || t.relname || '|' || a.attname FROM pg_constraint c
      JOIN pg_class t ON t.oid=c.conrelid JOIN pg_namespace n ON n.oid=t.relnamespace
      JOIN pg_attribute a ON a.attrelid=c.conrelid AND a.attnum=ANY(c.conkey)
     WHERE c.contype='f' AND c.confrelid='public.properties'::regclass AND n.nspname='public'
  LOOP
    DECLARE v_tbl text := split_part(v_table_name, '|', 1); v_col text := split_part(v_table_name, '|', 2);
    BEGIN
      EXECUTE format('UPDATE %s SET %I = $1 WHERE %I = $2', v_tbl, v_col, v_col) USING p_keep_id, p_drop_id;
      GET DIAGNOSTICS v_count = ROW_COUNT;
      IF v_count > 0 THEN v_rewired := v_rewired || jsonb_build_object(v_tbl || '.' || v_col, v_count); END IF;
    EXCEPTION
      WHEN unique_violation THEN
        -- v_tbl carries a "public." prefix (schemaname.relname); gov_merge_fold_table wants the bare name.
        v_fold_detail := public.gov_merge_fold_table(split_part(v_tbl, '.', 2), v_col, p_keep_id, p_drop_id);
        v_rewired := v_rewired || jsonb_build_object(v_tbl || '.' || v_col, v_fold_detail);
      WHEN OTHERS THEN
        v_rewired := v_rewired || jsonb_build_object(v_tbl || '.' || v_col || '_error', SQLERRM);
    END;
  END LOOP;
  BEGIN
    DELETE FROM public.properties WHERE property_id = p_drop_id;
    GET DIAGNOSTICS v_count = ROW_COUNT;
  EXCEPTION WHEN OTHERS THEN
    v_count := 0;
    v_rewired := v_rewired || jsonb_build_object('properties_delete_failed', SQLERRM);
  END;
  RETURN jsonb_build_object('keep_id', p_keep_id, 'drop_id', p_drop_id, 'rewired', v_rewired,
    'property_deleted', v_count, 'merge_function_version', 'gov_merge1_fold_on_collision_2026_09_05');
END;
$function$;
