// ============================================================================
// OC3 — the one to-do list: fetch + render operator_notes into a grouped
// Markdown inbox. Shared by scripts/render-operator-inbox.mjs and the MCP
// read tool get_operator_inbox, so both surfaces read the same list (spec
// §6: "sorts to the same one to-do list").
// ============================================================================

import { opsQuery } from './ops-db.js';

const SEVERITY_RANK = { high: 0, medium: 1, low: 2 };

/** Fetches every note that still needs attention (open/routed/in_progress),
 * optionally scoped to one thread. */
export async function fetchInboxNotes({ thread } = {}, deps = {}) {
  const q = deps.opsQuery || opsQuery;
  let path = `operator_notes?disposition=in.(open,routed,in_progress)`
    + `&select=id,channel,raw_text,note_type,lane,severity,routed_to,disposition,dedupe_of,metadata,received_at,received_from`
    + `&order=received_at.desc&limit=500`;
  if (thread) path += `&routed_to=eq.${encodeURIComponent(thread)}`;
  const r = await q('GET', path);
  return Array.isArray(r?.data) ? r.data : [];
}

/** Pure. Groups + sorts notes: by routed_to thread (unrouted last), then by
 * severity (high first), then newest first within a severity. */
export function groupAndSortInbox(notes) {
  const groups = new Map();
  for (const n of notes || []) {
    const thread = n.routed_to || '(unrouted)';
    if (!groups.has(thread)) groups.set(thread, []);
    groups.get(thread).push(n);
  }
  for (const list of groups.values()) {
    list.sort((a, b) => {
      const sa = SEVERITY_RANK[a.severity] ?? 3;
      const sb = SEVERITY_RANK[b.severity] ?? 3;
      if (sa !== sb) return sa - sb;
      return new Date(b.received_at || 0) - new Date(a.received_at || 0);
    });
  }
  // Sort threads: named threads alphabetically, "(unrouted)" always last.
  const threads = [...groups.keys()].sort((a, b) => {
    if (a === '(unrouted)') return 1;
    if (b === '(unrouted)') return -1;
    return a.localeCompare(b);
  });
  return threads.map((thread) => ({ thread, notes: groups.get(thread) }));
}

function noteLine(n) {
  const type = n.note_type || 'untriaged';
  const sev = n.severity || 'unknown';
  const title = n.metadata?.title || String(n.raw_text || '').replace(/\s+/g, ' ').slice(0, 90);
  const backlogRef = n.metadata?.duplicate_of_backlog_row ? ` · backlog:${n.metadata.duplicate_of_backlog_row}` : '';
  const dupeRef = n.dedupe_of ? ` · dup-of:${n.dedupe_of}` : '';
  return `- \`${n.id}\` **[${type}/${sev}]** ${title} _(${n.channel}, ${n.disposition}${backlogRef}${dupeRef})_`;
}

/** Pure. Renders the grouped inbox to Markdown with a GENERATED header
 * (per the repo's GENERATED-file convention — never hand-edited). */
export function renderInboxMarkdown(grouped, { generatedAt = new Date().toISOString() } = {}) {
  const totalNotes = grouped.reduce((sum, g) => sum + g.notes.length, 0);
  const lines = [];
  lines.push('<!-- GENERATED by scripts/render-operator-inbox.mjs — do not hand-edit. -->');
  lines.push('# Operator Inbox');
  lines.push('');
  lines.push(`Generated ${generatedAt}. ${totalNotes} open item(s) across ${grouped.length} thread(s).`);
  lines.push('');
  lines.push('One funnel, every channel (in-app Note, tagged Outlook, Teams, MCP `log_operator_note`, '
    + 'Cowork/Claude Code) → this list, grouped by owner thread. Read this alongside `responses/` at the '
    + 'start of every Claude Code / Cowork turn. Source: `operator_notes` — '
    + '[`docs/architecture/operator_note_contract.md`](../architecture/operator_note_contract.md).');
  lines.push('');
  if (totalNotes === 0) {
    lines.push('_Nothing open._');
    return lines.join('\n') + '\n';
  }
  for (const { thread, notes } of grouped) {
    lines.push(`## ${thread} (${notes.length})`);
    lines.push('');
    for (const n of notes) lines.push(noteLine(n));
    lines.push('');
  }
  return lines.join('\n');
}
