// ============================================================================
// Team Context — Shared utility for team track record and recent sales data
// Life Command Center — Wave 2: Template Variable Resolution
//
// Resolves the {{team.*}} variables used across most email templates:
//   - team.track_record_summary  — boilerplate credibility paragraph
//   - team.recent_sales_table    — formatted recent transaction table
//   - team.transaction_count     — total transactions
//   - team.transaction_volume    — total dollar volume
//
// Queries both GOV and DIA Supabase databases for sales data.
// Results are cached per-domain for 24 hours via the template engine.
// ============================================================================

import { opsQuery } from './ops-db.js';

// NorthMarq / Briggs team track record summaries by domain
// These are updated quarterly — stored here as code constants so they're
// always available even if the DB is down. Updated by Scott periodically.
const TRACK_RECORD = {
  government: {
    summary: `NorthMarq operates one of the industry's leading government-leased practice groups. Our track record includes hundreds of transactions for a cumulative value of billions of dollars over the past five years where a governmental agency or government contractor accounted for more than 50% of the income generated by the property at the time of sale. Please do not hesitate to reach out if there is anything we can do to assist. We look forward to the opportunity to leverage our firm's collective specialization, knowledge, track record and expertise to your benefit.`,
    fallback_count: 810,
    fallback_volume: '$4.99 billion',
  },
  dialysis: {
    summary: `NorthMarq operates one of the industry's leading dialysis-leased practice groups with extensive transactions where a dialysis operator is directly the tenant. Our healthcare track record includes hundreds of transactions for significant cumulative value. Please do not hesitate to reach out if there is anything we can do to assist. We look forward to the opportunity to leverage our firm's collective specialization, knowledge, track record and expertise to your benefit.`,
    fallback_count: 265,
    fallback_volume: '$1.66 billion',
  },
};

/**
 * Get the team track record summary paragraph for a given domain.
 * This is the boilerplate credibility paragraph used in most outreach emails.
 *
 * @param {string} domain - 'government' or 'dialysis'
 * @returns {string} The track record summary paragraph
 */
export function getTrackRecordSummary(domain) {
  const record = TRACK_RECORD[domain] || TRACK_RECORD.government;
  return record.summary;
}

/**
 * Build a formatted recent sales table for email inclusion.
 * Queries the domain-specific Supabase DB for recent NorthMarq transactions.
 *
 * This is designed to be called during template draft generation to populate
 * the {{team.recent_sales_table}} variable.
 *
 * @param {string} domain - 'government' or 'dialysis'
 * @param {object} [options]
 * @param {number} [options.limit=10] - Max number of sales to include
 * @param {string} [options.state] - Filter by state if provided
 * @returns {Promise<{ table: string, count: number, volume: string }>}
 */
export async function buildRecentSalesTable(domain, options = {}) {
  const { limit = 10, state } = options;

  // We need to query the domain DBs — these are accessed via data-proxy
  // For now, use the opsQuery with the data-proxy route
  let proxyRoute;
  if (domain === 'government') {
    proxyRoute = `data-proxy?_source=gov&table=sales_transactions&select=address,city,state,agency,sf_leased,noi,noi_psf,firm_term_years,expenses,sold_price,sold_price_psf,sold_cap_rate,sale_date,buyer&is_northmarq=eq.true&order=sale_date.desc&limit=${limit}`;
  } else {
    proxyRoute = `data-proxy?_source=dia&table=sales_transactions&select=address,city,state,tenant,building_size,noi,noi_psf,firm_term_years,expenses,sold_price,sold_price_psf,sold_cap_rate,sale_date,buyer&order=sale_date.desc&limit=${limit}`;
  }

  if (state) {
    proxyRoute += `&state=eq.${state}`;
  }

  // Note: This queries through the LCC API data-proxy, not directly.
  // In the Context Broker edge function, we query the domain DBs directly.
  // This utility is for the Vercel-side template engine.

  // For now, return a structured format that can be used by the template engine
  // The actual DB query happens in the Context Broker or via data-proxy
  return {
    table: null, // Will be populated by caller
    count: 0,
    volume: '$0',
  };
}

/**
 * Format sales data into an email-friendly table string.
 * Used by both the Vercel template engine and the Context Broker.
 *
 * @param {object[]} sales - Array of sales transaction records
 * @param {string} domain - 'government' or 'dialysis'
 * @returns {string} Formatted table string for email embedding
 */
export function formatSalesTable(sales, domain) {
  if (!sales || sales.length === 0) return '';

  const lines = [];

  if (domain === 'government') {
    // Government format: Tenant | Type | City | State | RBA | NOI | Term | Cap | Sold Price | Date
    for (let i = 0; i < sales.length; i++) {
      const s = sales[i];
      const city = s.city || '';
      const state = s.state || '';
      const tenant = s.agency || s.tenant || '';
      const rba = s.sf_leased || s.rba || s.building_size || '';
      const noi = s.noi ? `$${Number(s.noi).toLocaleString()}` : '';
      const term = s.firm_term_years || s.total_term_years || '';
      const cap = s.sold_cap_rate ? `${s.sold_cap_rate}%` : '';
      const price = s.sold_price ? `$${Number(s.sold_price).toLocaleString()}` : '';
      const date = s.sale_date ? new Date(s.sale_date).toLocaleDateString('en-US', { month: 'short', year: '2-digit' }) : '';

      lines.push(`${i + 1}. ${tenant} | ${city}, ${state} | ${rba ? Number(rba).toLocaleString() + ' SF' : ''} | NOI: ${noi} | Term: ${term} yr | Cap: ${cap} | ${price} | ${date}`);
    }
  } else {
    // Dialysis format: Operator | Location | Built | RBA | Rent | Term | Cap | Sold Price | Date
    for (let i = 0; i < sales.length; i++) {
      const s = sales[i];
      const location = [s.city, s.state].filter(Boolean).join(', ');
      const operator = s.tenant || s.operator || '';
      const rba = s.sf_leased || s.rba || s.building_size || '';
      const rent = s.noi ? `$${Number(s.noi).toLocaleString()}` : '';
      const term = s.firm_term_years || '';
      const cap = s.sold_cap_rate ? `${s.sold_cap_rate}%` : '';
      const price = s.sold_price ? `$${Number(s.sold_price).toLocaleString()}` : '';
      const date = s.sale_date ? new Date(s.sale_date).toLocaleDateString('en-US', { month: 'short', year: '2-digit' }) : '';

      lines.push(`${i + 1}. ${operator} | ${location} | ${rba ? Number(rba).toLocaleString() + ' SF' : ''} | Rent: ${rent} | Term: ${term} yr | Cap: ${cap} | ${price} | ${date}`);
    }
  }

  return lines.join('\n');
}

/**
 * Build the full team context object for template variable resolution.
 * This merges track record summary + recent sales into a single object
 * that gets injected into the template context under the 'team' key.
 *
 * @param {string} domain - 'government' or 'dialysis'
 * @param {object[]} [recentSales] - Pre-fetched sales data (optional)
 * @returns {object} The team context object
 */
export function buildTeamContext(domain, recentSales) {
  const record = TRACK_RECORD[domain] || TRACK_RECORD.government;

  return {
    track_record_summary: record.summary,
    recent_sales_table: recentSales ? formatSalesTable(recentSales, domain) : null,
    transaction_count: record.fallback_count,
    transaction_volume: record.fallback_volume,
  };
}
