// ============================================================================
// Team Context — Shared utility for team track record and recent sales data
// Life Command Center — Wave 2: Template Variable Resolution
//
// Resolves the {{team.*}} variables used across most email templates:
//   - team.track_record_summary  — boilerplate credibility paragraph
//   - team.recent_sales_table    — formatted recent transaction table
//   - team.transaction_count     — total transactions
//   - team.transaction_volume    — total dollar volume
//
// Queries both GOV and DIA Supabase databases for sales data.
// Results are cached per-domain for 24 hours via the template engine.
// ============================================================================

import { opsQuery } from './ops-db.js';

// ============================================================================
// DOMAIN DB QUERY — direct fetch to GOV/DIA Supabase instances
// ============================================================================

/**
 * Query a domain-specific Supabase database directly (GOV or DIA).
 * This bypasses data-proxy (which is an HTTP endpoint) for server-side use.
 *
 * @param {'gov'|'dia'} source - Which domain DB to query
 * @param {string} path - PostgREST path with query params (e.g., 'sales_transactions?is_northmarq=eq.true&limit=10')
 * @returns {Promise<{ ok: boolean, data: any[], count: number }>}
 */
async function domainQuery(source, path) {
  const urlEnv = source === 'gov' ? 'GOV_SUPABASE_URL' : 'DIA_SUPABASE_URL';
  const keyEnv = source === 'gov' ? 'GOV_SUPABASE_KEY' : 'DIA_SUPABASE_KEY';
  const baseUrl = process.env[urlEnv];
  const apiKey = process.env[keyEnv];

  if (!baseUrl || !apiKey) {
    console.warn(`[team-context] ${source.toUpperCase()} DB not configured (${urlEnv}/${keyEnv})`);
    return { ok: false, data: [], count: 0 };
  }

  const url = `${baseUrl}/rest/v1/${path}`;
  try {
    const resp = await fetch(url, {
      method: 'GET',
      headers: {
        'apikey': apiKey,
        'Authorization': `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
        'Prefer': 'count=exact'
      }
    });

    if (!resp.ok) {
      console.warn(`[team-context] domainQuery ${source} failed: ${resp.status}`);
      return { ok: false, data: [], count: 0 };
    }

    const data = await resp.json();
    const contentRange = resp.headers.get('content-range');
    let count = Array.isArray(data) ? data.length : 0;
    if (contentRange) {
      const m = contentRange.match(/\/(\d+)/);
      if (m) count = parseInt(m[1], 10);
    }

    return { ok: true, data: Array.isArray(data) ? data : [], count };
  } catch (err) {
    console.error(`[team-context] domainQuery error:`, err.message);
    return { ok: false, data: [], count: 0 };
  }
}

// NorthMarq / Briggs team track record summaries by domain
// These are firm-level marketing numbers from NorthMarq's internal production
// reports — NOT derived from our CoStar-sourced DBs (which only capture public
// comps). Updated by Scott from NorthMarq quarterly production reports.
//
// LAST UPDATED: 2026-04-07 (Q1 2026 refresh)
// SOURCE: NorthMarq NNN Group internal production dashboard
// NEXT REVIEW: Q2 2026
const TRACK_RECORD = {
  government: {
    summary: `NorthMarq operates one of the industry's leading government-leased practice groups. Our track record includes more than 850 transactions representing over $5.2 billion in cumulative value where a governmental agency or government contractor accounted for more than 50% of the income generated by the property at the time of sale. We look forward to the opportunity to leverage our firm's collective specialization, knowledge, track record and expertise to your benefit.`,
    fallback_count: 855,
    fallback_volume: '$5.21 billion',
    last_updated: '2026-04-07',
  },
  dialysis: {
    summary: `NorthMarq operates one of the industry's leading dialysis-leased practice groups with more than 290 transactions representing over $1.8 billion in cumulative value where a dialysis operator is directly the tenant. Our healthcare track record is unmatched in the net lease space. We look forward to the opportunity to leverage our firm's collective specialization, knowledge, track record and expertise to your benefit.`,
    fallback_count: 293,
    fallback_volume: '$1.82 billion',
    last_updated: '2026-04-07',
  },
};

/**
 * Get the team track record summary paragraph for a given domain.
 * This is the boilerplate credibility paragraph used in most outreach emails.
 *
 * @param {string} domain - 'government' or 'dialysis'
 * @returns {string} The track record summary paragraph
 */
export function getTrackRecordSummary(domain) {
  const record = TRACK_RECORD[domain] || TRACK_RECORD.government;
  return record.summary;
}

/**
 * Build a formatted recent sales table for email inclusion.
 * Queries the domain-specific Supabase DB for recent NorthMarq transactions.
 *
 * This is designed to be called during template draft generation to populate
 * the {{team.recent_sales_table}} variable.
 *
 * @param {string} domain - 'government' or 'dialysis'
 * @param {object} [options]
 * @param {number} [options.limit=10] - Max number of sales to include
 * @param {string} [options.state] - Filter by state if provided
 * @returns {Promise<{ table: string, count: number, volume: string }>}
 */
export async function buildRecentSalesTable(domain, options = {}) {
  const { limit = 10, state } = options;

  // Query domain DBs directly for NorthMarq transactions.
  // NOTE: DIA schema differs from GOV — sales_transactions there has no
  // denormalized address/tenant/noi columns (those live on a separate
  // properties table) and no is_northmarq flag. Until we build a proper
  // view for it, short-circuit dialysis to the static TRACK_RECORD fallback
  // so we don't spam 400s to the Vercel logs.
  if (domain !== 'government') {
    const record = TRACK_RECORD[domain] || TRACK_RECORD.government;
    return {
      table: null,
      count: record.fallback_count,
      volume: record.fallback_volume,
    };
  }

  let path = `sales_transactions?select=address,city,state,agency,sf_leased,noi,noi_psf,firm_term_years,sold_price,sold_price_psf,sold_cap_rate,sale_date,buyer&is_northmarq=eq.true&order=sale_date.desc&limit=${limit}`;
  if (state) {
    path += `&state=eq.${state}`;
  }

  const result = await domainQuery('gov', path);

  if (!result.ok || !result.data.length) {
    // Fall back to TRACK_RECORD constants if DB query fails
    const record = TRACK_RECORD[domain] || TRACK_RECORD.government;
    return {
      table: null,
      count: record.fallback_count,
      volume: record.fallback_volume,
    };
  }

  const sales = result.data;
  const table = formatSalesTable(sales, domain);

  // Compute total volume from returned rows
  const totalVolume = sales.reduce((sum, s) => sum + (Number(s.sold_price) || 0), 0);
  const volumeStr = totalVolume >= 1e9
    ? `$${(totalVolume / 1e9).toFixed(2)} billion`
    : totalVolume >= 1e6
    ? `$${(totalVolume / 1e6).toFixed(1)} million`
    : `$${totalVolume.toLocaleString()}`;

  return {
    table,
    count: sales.length,
    volume: volumeStr,
    sales, // raw data for callers that need it
  };
}

/**
 * Format sales data into an email-friendly table string.
 * Used by both the Vercel template engine and the Context Broker.
 *
 * @param {object[]} sales - Array of sales transaction records
 * @param {string} domain - 'government' or 'dialysis'
 * @returns {string} Formatted table string for email embedding
 */
export function formatSalesTable(sales, domain) {
  if (!sales || sales.length === 0) return '';

  const lines = [];

  if (domain === 'government') {
    // Government format: Tenant | Type | City | State | RBA | NOI | Term | Cap | Sold Price | Date
    for (let i = 0; i < sales.length; i++) {
      const s = sales[i];
      const city = s.city || '';
      const state = s.state || '';
      const tenant = s.agency || s.tenant || '';
      const rba = s.rba || s.building_size || s.sf_leased || '';
      const noi = s.noi ? `$${Number(s.noi).toLocaleString()}` : '';
      const term = s.firm_term_years || s.total_term_years || '';
      const cap = s.sold_cap_rate ? `${s.sold_cap_rate}%` : '';
      const price = s.sold_price ? `$${Number(s.sold_price).toLocaleString()}` : '';
      const date = s.sale_date ? new Date(s.sale_date).toLocaleDateString('en-US', { month: 'short', year: '2-digit' }) : '';

      lines.push(`${i + 1}. ${tenant} | ${city}, ${state} | ${rba ? Number(rba).toLocaleString() + ' SF' : ''} | NOI: ${noi} | Term: ${term} yr | Cap: ${cap} | ${price} | ${date}`);
    }
  } else {
    // Dialysis format: Operator | Location | Built | RBA | Rent | Term | Cap | Sold Price | Date
    for (let i = 0; i < sales.length; i++) {
      const s = sales[i];
      const location = [s.city, s.state].filter(Boolean).join(', ');
      const operator = s.tenant || s.operator || '';
      const rba = s.rba || s.building_size || s.sf_leased || '';
      const rent = s.noi ? `$${Number(s.noi).toLocaleString()}` : '';
      const term = s.firm_term_years || '';
      const cap = s.sold_cap_rate ? `${s.sold_cap_rate}%` : '';
      const price = s.sold_price ? `$${Number(s.sold_price).toLocaleString()}` : '';
      const date = s.sale_date ? new Date(s.sale_date).toLocaleDateString('en-US', { month: 'short', year: '2-digit' }) : '';

      lines.push(`${i + 1}. ${operator} | ${location} | ${rba ? Number(rba).toLocaleString() + ' SF' : ''} | Rent: ${rent} | Term: ${term} yr | Cap: ${cap} | ${price} | ${date}`);
    }
  }

  return lines.join('\n');
}

/**
 * Build the full team context object for template variable resolution.
 * This merges track record summary + recent sales into a single object
 * that gets injected into the template context under the 'team' key.
 *
 * @param {string} domain - 'government' or 'dialysis'
 * @param {object[]} [recentSales] - Pre-fetched sales data (optional)
 * @returns {object} The team context object
 */
export function buildTeamContext(domain, recentSales) {
  const record = TRACK_RECORD[domain] || TRACK_RECORD.government;

  return {
    track_record_summary: record.summary,
    recent_sales_table: recentSales ? formatSalesTable(recentSales, domain) : null,
    transaction_count: record.fallback_count,
    transaction_volume: record.fallback_volume,
    track_record_last_updated: record.last_updated || null,
  };
}

/**
 * Build the full team context with live sales data from the domain DB.
 * Async version that fetches recent sales automatically.
 *
 * @param {string} domain - 'government' or 'dialysis'
 * @param {object} [options]
 * @param {number} [options.limit=10] - Max sales to include
 * @param {string} [options.state] - Filter by state
 * @returns {Promise<object>} The team context with live sales table
 */
export async function buildTeamContextWithSales(domain, options = {}) {
  const record = TRACK_RECORD[domain] || TRACK_RECORD.government;
  const salesResult = await buildRecentSalesTable(domain, options);

  return {
    track_record_summary: record.summary,
    recent_sales_table: salesResult.table,
    recent_sales_count: salesResult.count,
    recent_sales_volume: salesResult.volume,
    transaction_count: record.fallback_count,
    transaction_volume: record.fallback_volume,
    track_record_last_updated: record.last_updated || null,
  };
}
