// OC3 — the one to-do list: grouping/sorting + Markdown render. Pure
// functions, no network.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { groupAndSortInbox, renderInboxMarkdown } from '../api/_shared/operator-inbox.js';
import { parseBacklogIndex } from '../scripts/generate-operator-note-backlog-index.mjs';

const NOTES = [
  { id: '1', channel: 'in_app_note', raw_text: 'low sev automation note', note_type: 'idea', severity: 'low', routed_to: 'automation', disposition: 'routed', received_at: '2026-09-01T00:00:00Z' },
  { id: '2', channel: 'mcp', raw_text: 'high sev automation bug', note_type: 'bug', severity: 'high', routed_to: 'automation', disposition: 'open', received_at: '2026-09-02T00:00:00Z' },
  { id: '3', channel: 'teams', raw_text: 'comps note', note_type: 'question', severity: 'medium', routed_to: 'comps', disposition: 'open', received_at: '2026-09-03T00:00:00Z' },
  { id: '4', channel: 'in_app_note', raw_text: 'no route yet', note_type: null, severity: null, routed_to: null, disposition: 'open', received_at: '2026-09-04T00:00:00Z' },
];

test('groupAndSortInbox groups by thread and puts high severity first within a thread', () => {
  const grouped = groupAndSortInbox(NOTES);
  const automation = grouped.find((g) => g.thread === 'automation');
  assert.ok(automation);
  assert.equal(automation.notes[0].id, '2'); // high severity first
  assert.equal(automation.notes[1].id, '1');
});

test('groupAndSortInbox sorts threads alphabetically with (unrouted) always last', () => {
  const grouped = groupAndSortInbox(NOTES);
  const threadNames = grouped.map((g) => g.thread);
  assert.deepEqual(threadNames, ['automation', 'comps', '(unrouted)']);
});

test('renderInboxMarkdown carries a GENERATED header and every note id', () => {
  const grouped = groupAndSortInbox(NOTES);
  const md = renderInboxMarkdown(grouped, { generatedAt: '2026-09-11T00:00:00Z' });
  assert.match(md, /GENERATED by scripts\/render-operator-inbox\.mjs/);
  assert.match(md, /## automation \(2\)/);
  assert.match(md, /## comps \(1\)/);
  assert.match(md, /## \(unrouted\) \(1\)/);
  for (const n of NOTES) assert.match(md, new RegExp('`' + n.id + '`'));
});

test('renderInboxMarkdown reports "Nothing open." on an empty inbox', () => {
  const md = renderInboxMarkdown([], { generatedAt: '2026-09-11T00:00:00Z' });
  assert.match(md, /Nothing open\./);
});

test('renderInboxMarkdown surfaces a backlog dedupe reference on the note line', () => {
  const withBacklog = [{ ...NOTES[0], metadata: { duplicate_of_backlog_row: 'P196' } }];
  const grouped = groupAndSortInbox(withBacklog);
  const md = renderInboxMarkdown(grouped);
  assert.match(md, /backlog:P196/);
});

// ---------------------------------------------------------------------------
// Backlog index parser (dedupe-against-PLANNED-BACKLOG.md source).
// ---------------------------------------------------------------------------

const SAMPLE_MD = `
## P18 — some section

| # | Item | State | Source |
|---|---|---|---|
| EB1 | ✅ **Shipped** — some description of EB1's work. | ✅ | STATUS.md |
| OC1 | **Intake v1** — one endpoint, per-channel adapters. | 🟢 | spec §6 |
| not a row | | | |
`;

test('parseBacklogIndex extracts row_id + title from PLANNED-BACKLOG-shaped tables', () => {
  const rows = parseBacklogIndex(SAMPLE_MD);
  const ids = rows.map((r) => r.row_id);
  assert.ok(ids.includes('EB1'));
  assert.ok(ids.includes('OC1'));
  const eb1 = rows.find((r) => r.row_id === 'EB1');
  assert.match(eb1.title, /Shipped/);
});

test('parseBacklogIndex strips leading emoji/markdown noise from the title', () => {
  const rows = parseBacklogIndex(SAMPLE_MD);
  const eb1 = rows.find((r) => r.row_id === 'EB1');
  assert.doesNotMatch(eb1.title, /^\s*✅/);
});

test('parseBacklogIndex de-duplicates identical (row_id, title) pairs', () => {
  const dup = SAMPLE_MD + '\n| EB1 | ✅ **Shipped** — some description of EB1\'s work. | ✅ | STATUS.md |\n';
  const rows = parseBacklogIndex(dup);
  const eb1Rows = rows.filter((r) => r.row_id === 'EB1');
  assert.equal(eb1Rows.length, 1);
});
