import { getDialysisClient, getGovClient, jsonResponse, normalizeSFArray, ANTHROPIC_API_KEY, GOV_ANON_KEY, PA_LOG_ACTIVITY_URL } from "./utils.ts";
import type { SFActivity, SFAccount, SFContact } from "./utils.ts";

export async function handleHealth() {
  const checks: Record<string, string> = {};
  try { const d = getDialysisClient(); const { count, error } = await d.from("properties").select("property_id", { count: "exact", head: true }); checks.dialysis_db = error ? `error: ${error.message}` : `ok (${count} properties)`; } catch (e) { checks.dialysis_db = `error: ${(e as Error).message}`; }
  try { const g = getGovClient(); const { count, error } = await g.from("properties").select("property_id", { count: "exact", head: true }); checks.government_db = error ? `error: ${error.message}` : `ok (${count} properties)`; } catch (e) { checks.government_db = `error: ${(e as Error).message}`; }
  checks.anthropic_key = ANTHROPIC_API_KEY ? "configured" : "not set";
  checks.gov_key = GOV_ANON_KEY ? "configured" : "not set";
  checks.pa_log_activity_url = PA_LOG_ACTIVITY_URL ? "configured" : "not set";
  try { const d = getDialysisClient(); const { count } = await d.from("salesforce_accounts").select("id", { count: "exact", head: true }); checks.sf_accounts = `${count || 0} stored`; } catch (_) { checks.sf_accounts = 'table missing'; }
  try { const d = getDialysisClient(); const { count } = await d.from("salesforce_contacts").select("id", { count: "exact", head: true }); checks.sf_contacts = `${count || 0} stored`; } catch (_) { checks.sf_contacts = 'table missing'; }
  try { const d = getDialysisClient(); const { data } = await d.rpc("exec_sql", { query: `SELECT (SELECT count(*) FROM salesforce_activities) as total, (SELECT count(*) FROM salesforce_activities WHERE company_name IS NOT NULL) as with_company, (SELECT count(*) FROM salesforce_activities WHERE first_name IS NOT NULL) as with_contact` }).single(); if (data && data.total !== undefined) { checks.sf_activities = `${data.total} total, ${data.with_company} with company_name, ${data.with_contact} with contact_name`; } else { checks.sf_activities = 'count unavailable'; } } catch (_) { checks.sf_activities = 'error counting'; }
  try { const d = getDialysisClient(); const { count } = await d.from("outbound_activities").select("id", { count: "exact", head: true }); checks.outbound_activities = `${count || 0} logged`; } catch (_) { checks.outbound_activities = 'table missing'; }
  try { const d = getDialysisClient(); const { data } = await d.from("bd_config").select("category, daily_target").order("sort_order"); checks.bd_config = data ? `${data.length} categories configured` : 'not configured'; } catch (_) { checks.bd_config = 'table missing'; }
  try { const d = getDialysisClient(); const { count } = await d.from("salesforce_tasks").select("id", { count: "exact", head: true }); checks.sf_tasks = `${count || 0} stored`; } catch (_) { checks.sf_tasks = 'table missing'; }
  try { const d = getDialysisClient(); const { count } = await d.from("flagged_emails").select("id", { count: "exact", head: true }); checks.flagged_emails = `${count || 0} stored`; } catch (_) { checks.flagged_emails = 'table missing'; }
  return jsonResponse({ status: "ok", version: 52, checks, timestamp: new Date().toISOString() });
}

export async function handleSearchProperty(body: { query: string; source_db?: string; limit?: number }) {
  const { query, source_db, limit = 10 } = body;
  if (!query) return jsonResponse({ error: "query is required" }, 400);
  const searchTerm = `%${query}%`;
  const results: unknown[] = [];
  if (!source_db || source_db === "dialysis") { try { const d = getDialysisClient(); const { data, error } = await d.from("properties").select("property_id, tenant, building_name, address, city, state, zip_code, building_size, year_built").or(`tenant.ilike.${searchTerm},building_name.ilike.${searchTerm},address.ilike.${searchTerm},city.ilike.${searchTerm}`).limit(limit); if (!error && data) results.push(...data.map((r: Record<string, unknown>) => ({ ...r, source: "dialysis", display_name: r.tenant || r.building_name || r.address }))); } catch (_) {} }
  if (!source_db || source_db === "government") { try { const g = getGovClient(); const { data, error } = await g.from("properties").select("property_id, address, city, state, zip_code, sf_leased, year_built, agency, agency_full_name").or(`address.ilike.${searchTerm},city.ilike.${searchTerm},agency_full_name.ilike.${searchTerm}`).limit(limit); if (!error && data) results.push(...data.map((r: Record<string, unknown>) => ({ ...r, source: "government", display_name: r.address || r.agency_full_name }))); } catch (_) {} }
  return jsonResponse({ results, count: results.length });
}

export async function handleEnrich(body: { property_name: string; city?: string; state?: string }) {
  const { property_name, city, state } = body;
  if (!property_name && !city) return jsonResponse({ error: "property_name or city is required" }, 400);
  const enrichment: Record<string, unknown> = { property_name, city, state, sources: {} };
  try { const d = getDialysisClient(); let prop: Record<string, unknown> | null = null; if (property_name && city && state) { const { data } = await d.from("properties").select("*").ilike("city", city).eq("state", state).or(`tenant.ilike.%${property_name}%,building_name.ilike.%${property_name}%`).limit(1); if (data && data.length > 0) prop = data[0]; } if (!prop && property_name) { const { data } = await d.from("properties").select("*").or(`tenant.ilike.%${property_name}%,building_name.ilike.%${property_name}%`).limit(1); if (data && data.length > 0) prop = data[0]; } if (prop) { enrichment.dialysis_property = prop; (enrichment.sources as Record<string, boolean>).dialysis = true; const pid = prop.property_id; const [leaseRes, salesRes, contactsRes, ownerRes] = await Promise.all([d.from("leases").select("*").eq("property_id", pid).order("lease_start", { ascending: false }).limit(5), d.from("sales_transactions").select("*").eq("property_id", pid).order("sale_date", { ascending: false }).limit(10), d.from("contacts").select("*").eq("entity_id", pid.toString()).limit(10), d.from("true_owners").select("*").eq("true_owner_id", prop.true_owner_id || "__none__").limit(1)]); enrichment.leases = leaseRes.data || []; enrichment.sales_transactions = salesRes.data || []; enrichment.contacts = contactsRes.data || []; enrichment.true_owner = ownerRes.data?.[0] || null; } } catch (e) { enrichment.dialysis_error = (e as Error).message; }
  try { const g = getGovClient(); let govProp: Record<string, unknown> | null = null; if (property_name && city && state) { const { data } = await g.from("properties").select("*").ilike("city", city).eq("state", state).or(`address.ilike.%${property_name}%,agency_full_name.ilike.%${property_name}%`).limit(1); if (data && data.length > 0) govProp = data[0]; } if (!govProp && property_name) { const { data } = await g.from("properties").select("*").or(`address.ilike.%${property_name}%,agency_full_name.ilike.%${property_name}%`).limit(1); if (data && data.length > 0) govProp = data[0]; } if (govProp) { enrichment.government_property = govProp; (enrichment.sources as Record<string, boolean>).government = true; } } catch (e) { enrichment.government_error = (e as Error).message; }
  return jsonResponse(enrichment);
}

export async function handleChat(body: { message: string; context?: Record<string, unknown>; history?: Array<{ role: string; content: string }> }) {
  const { message, context, history } = body;
  if (!message) return jsonResponse({ error: "message is required" }, 400);
  if (!ANTHROPIC_API_KEY) return jsonResponse({ error: "Anthropic API key not configured" }, 500);
  const systemPrompt = `You are an AI sales strategy copilot for a commercial real estate (CRE) business development professional at Northmarq, focused on net lease investment properties. Be concise but thorough. Reference actual data points. Always suggest next steps.`;
  const messages = [...(history || []).map((h: { role: string; content: string }) => ({ role: h.role, content: h.content })), { role: "user", content: message }];
  try { const resp = await fetch("https://api.anthropic.com/v1/messages", { method: "POST", headers: { "Content-Type": "application/json", "x-api-key": ANTHROPIC_API_KEY, "anthropic-version": "2023-06-01" }, body: JSON.stringify({ model: "claude-sonnet-4-20250514", max_tokens: 1500, system: systemPrompt, messages }) }); const result = await resp.json(); if (!resp.ok) return jsonResponse({ error: "Claude API error", details: result }, resp.status); return jsonResponse({ response: result.content?.[0]?.text || "", usage: result.usage }); } catch (e) { return jsonResponse({ error: "Failed to call Claude API", details: (e as Error).message }, 500); }
}

export async function handleSyncActivities(req: Request, body: { activities?: SFActivity[]; activity?: SFActivity; accounts?: SFAccount[] | { value?: SFAccount[] }; contacts?: SFContact[] | { value?: SFContact[] }; }) {
  const activities: SFActivity[] = body.activities || (body.activity ? [body.activity] : []);
  if (activities.length === 0) return jsonResponse({ error: "No activities provided" }, 400);
  const invalid = activities.filter(a => !a.sf_task_id);
  if (invalid.length > 0) return jsonResponse({ error: `${invalid.length} missing sf_task_id` }, 400);
  const d = getDialysisClient();
  const results = { upserted: 0, errors: [] as string[], accounts_stored: 0, contacts_stored: 0, company_names_resolved: 0, contact_names_resolved: 0, names_linked: 0 };
  const accountsList = normalizeSFArray<SFAccount>(body.accounts as SFAccount[] | { value?: SFAccount[] });
  if (accountsList.length > 0) { const accBatch = accountsList.map(a => { const sfId = (a.Id || a.id || '') as string; const sfName = (a.Name || a.name || '') as string; if (!sfId) return null; return { sf_account_id: sfId, name: sfName || null, billing_city: (a.BillingCity || null) as string | null, billing_state: (a.BillingState || null) as string | null, updated_at: new Date().toISOString() }; }).filter(Boolean); if (accBatch.length > 0) { const bSize = 100; for (let i = 0; i < accBatch.length; i += bSize) { const b = accBatch.slice(i, i + bSize); const { data, error } = await d.from("salesforce_accounts").upsert(b, { onConflict: "sf_account_id", ignoreDuplicates: false }).select("sf_account_id"); if (!error) results.accounts_stored += data?.length || b.length; } } }
  const contactsList = normalizeSFArray<SFContact>(body.contacts as SFContact[] | { value?: SFContact[] });
  if (contactsList.length > 0) { const ctBatch = contactsList.map(c => { const sfId = (c.Id || c.id || '') as string; if (!sfId) return null; return { sf_contact_id: sfId, first_name: (c.FirstName || c.firstName || c.first_name || null) as string | null, last_name: (c.LastName || c.lastName || c.last_name || null) as string | null, email: (c.Email || c.email || null) as string | null, phone: (c.Phone || c.phone || null) as string | null, sf_account_id: (c.AccountId || c.accountId || c.account_id || null) as string | null, updated_at: new Date().toISOString() }; }).filter(Boolean); if (ctBatch.length > 0) { const bSize = 100; for (let i = 0; i < ctBatch.length; i += bSize) { const b = ctBatch.slice(i, i + bSize); const { data, error } = await d.from("salesforce_contacts").upsert(b, { onConflict: "sf_contact_id", ignoreDuplicates: false }).select("sf_contact_id"); if (error) results.errors.push(`Contacts batch ${i}: ${error.message}`); else results.contacts_stored += data?.length || b.length; } } }
  const batchSize = 50;
  for (let i = 0; i < activities.length; i += batchSize) { const batch = activities.slice(i, i + batchSize).map(a => ({ sf_task_id: a.sf_task_id, subject: a.subject || null, first_name: a.first_name || null, last_name: a.last_name || null, sf_contact_id: a.sf_contact_id || null, company_name: a.company_name || null, sf_company_id: a.sf_company_id || null, company_address: a.company_address || null, company_city_state: a.company_city_state || null, assigned_to: a.assigned_to || null, nm_type: a.nm_type || null, activity_date: a.activity_date || null, nm_notes: a.nm_notes || null, task_subtype: a.task_subtype || null, email: a.email || null, phone: a.phone || null, status: a.status || null })); const { data, error } = await d.from("salesforce_activities").upsert(batch, { onConflict: "sf_task_id", ignoreDuplicates: false }).select("sf_task_id"); if (error) results.errors.push(`Batch ${i}: ${error.message}`); else results.upserted += data?.length || batch.length; }
  try { const { data } = await d.rpc("exec_sql", { query: `WITH resolved AS (UPDATE salesforce_activities sa SET company_name = sfa.name, company_city_state = COALESCE(sa.company_city_state, CASE WHEN sfa.billing_city IS NOT NULL AND sfa.billing_state IS NOT NULL THEN sfa.billing_city || ', ' || sfa.billing_state ELSE NULL END) FROM salesforce_accounts sfa WHERE sa.sf_company_id = sfa.sf_account_id AND sa.sf_company_id IS NOT NULL AND (sa.company_name IS NULL OR sa.company_name = '') RETURNING sa.sf_task_id) SELECT count(*) as cnt FROM resolved` }).single(); results.company_names_resolved = parseInt(data?.cnt || '0'); } catch (e) { results.errors.push(`Name resolve: ${(e as Error).message}`); }
  try { const { data } = await d.rpc("exec_sql", { query: `WITH resolved AS (UPDATE salesforce_activities sa SET first_name = COALESCE(sa.first_name, sfc.first_name), last_name = COALESCE(sa.last_name, sfc.last_name), email = COALESCE(sa.email, sfc.email), phone = COALESCE(sa.phone, sfc.phone) FROM salesforce_contacts sfc WHERE sa.sf_contact_id = sfc.sf_contact_id AND sa.sf_contact_id IS NOT NULL AND (sa.first_name IS NULL OR sa.first_name = '') RETURNING sa.sf_task_id) SELECT count(*) as cnt FROM resolved` }).single(); results.contact_names_resolved = parseInt(data?.cnt || '0'); } catch (e) { results.errors.push(`Contact resolve: ${(e as Error).message}`); }
  try { await d.rpc("exec_sql", { query: `UPDATE salesforce_activities sa SET contact_id = c.contact_id FROM contacts c WHERE sa.sf_contact_id = c.sf_contact_id AND sa.sf_contact_id IS NOT NULL AND sa.contact_id IS NULL` }).single(); } catch (_) {}
  try { await d.rpc("exec_sql", { query: `UPDATE salesforce_activities sa SET true_owner_id = t.true_owner_id FROM true_owners t WHERE sa.sf_company_id = t.sf_company_id AND sa.sf_company_id IS NOT NULL AND sa.true_owner_id IS NULL` }).single(); } catch (_) {}
  try { const { data } = await d.rpc("exec_sql", { query: `WITH matches AS (UPDATE salesforce_activities sa SET true_owner_id = t.true_owner_id FROM true_owners t WHERE lower(trim(sa.company_name)) = lower(trim(t.name)) AND sa.company_name IS NOT NULL AND sa.company_name != '' AND sa.true_owner_id IS NULL RETURNING sa.sf_task_id) SELECT count(*) as linked FROM matches` }).single(); results.names_linked = parseInt(data?.linked || '0'); } catch (_) {}
  try { await d.rpc("exec_sql", { query: `UPDATE true_owners t SET sf_company_id = sa.sf_company_id FROM salesforce_activities sa WHERE sa.true_owner_id = t.true_owner_id AND sa.sf_company_id IS NOT NULL AND (t.sf_company_id IS NULL OR t.sf_company_id = '') AND sa.sf_task_id IS NOT NULL` }).single(); } catch (_) {}
  return jsonResponse({ success: results.errors.length === 0, upserted: results.upserted, total_sent: activities.length, accounts_stored: results.accounts_stored, contacts_stored: results.contacts_stored, company_names_resolved: results.company_names_resolved, contact_names_resolved: results.contact_names_resolved, names_linked_to_owners: results.names_linked, errors: results.errors, version: 52 });
}

export async function handleSyncAccounts(_req: Request, body: { accounts?: SFAccount[] | { value?: SFAccount[] } }) {
  const accounts = normalizeSFArray<SFAccount>(body.accounts);
  if (accounts.length === 0) return jsonResponse({ error: "No accounts provided" }, 400);
  const d = getDialysisClient();
  const results = { upserted: 0, errors: [] as string[], total_received: accounts.length };
  const batchSize = 100;
  for (let i = 0; i < accounts.length; i += batchSize) { const batch = accounts.slice(i, i + batchSize).map(a => { const sfId = (a.Id || a.id || '') as string; const sfName = (a.Name || a.name || '') as string; if (!sfId) return null; return { sf_account_id: sfId, name: sfName || null, billing_city: (a.BillingCity || null) as string | null, billing_state: (a.BillingState || null) as string | null, updated_at: new Date().toISOString() }; }).filter(Boolean); if (batch.length === 0) continue; const { data, error } = await d.from("salesforce_accounts").upsert(batch, { onConflict: "sf_account_id", ignoreDuplicates: false }).select("sf_account_id"); if (error) results.errors.push(`Batch ${i}: ${error.message}`); else results.upserted += data?.length || batch.length; }
  let namesResolved = 0;
  try { const { data } = await d.rpc("exec_sql", { query: `WITH resolved AS (UPDATE salesforce_activities sa SET company_name = sfa.name, company_city_state = COALESCE(sa.company_city_state, CASE WHEN sfa.billing_city IS NOT NULL AND sfa.billing_state IS NOT NULL THEN sfa.billing_city || ', ' || sfa.billing_state ELSE NULL END) FROM salesforce_accounts sfa WHERE sa.sf_company_id = sfa.sf_account_id AND sa.sf_company_id IS NOT NULL AND (sa.company_name IS NULL OR sa.company_name = '') RETURNING sa.sf_task_id) SELECT count(*) as cnt FROM resolved` }).single(); namesResolved = parseInt(data?.cnt || '0'); } catch (_) {}
  let namesLinked = 0;
  try { const { data } = await d.rpc("exec_sql", { query: `WITH matches AS (UPDATE salesforce_activities sa SET true_owner_id = t.true_owner_id FROM true_owners t WHERE lower(trim(sa.company_name)) = lower(trim(t.name)) AND sa.company_name IS NOT NULL AND sa.company_name != '' AND sa.true_owner_id IS NULL RETURNING sa.sf_task_id) SELECT count(*) as linked FROM matches` }).single(); namesLinked = parseInt(data?.linked || '0'); } catch (_) {}
  return jsonResponse({ success: results.errors.length === 0, accounts_upserted: results.upserted, total_received: results.total_received, activity_names_resolved: namesResolved, names_linked_to_owners: namesLinked, errors: results.errors, version: 52 });
}