#!/usr/bin/env node
// ============================================================================
// LCC R2-L-1 — Schedule weekly template health rollup + persist history.
//
// One SQL migration (LCC Opps) + one new handler in api/operations.js. The
// JS handler was already added by the Cowork session that authored this
// patch. apply.mjs verifies both pieces are present and well-formed and
// appends the closeout block.
// ============================================================================

import { readFile, writeFile, access } from 'node:fs/promises';
import { constants } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '..', '..', '..');
const argv = new Set(process.argv.slice(2));
const DRY  = argv.has('--dry') || !argv.has('--apply');

function detectEol(s) {
  const crlf = (s.match(/\r\n/g) || []).length;
  const lf   = (s.match(/(^|[^\r])\n/g) || []).length;
  return crlf > lf ? '\r\n' : '\n';
}
function toEol(s, eol) { return s.replace(/\r\n/g, '\n').replace(/\n/g, eol); }
async function fileExists(p) {
  try { await access(p, constants.F_OK); return true; } catch { return false; }
}

async function verifyMigration(report) {
  const path = resolve(REPO_ROOT, 'supabase', 'migrations',
    '20260519120000_lcc_r2_l1_template_health_history_and_cron.sql');
  if (!await fileExists(path)) throw new Error('Migration not found at ' + path);
  const src = await readFile(path, 'utf8');
  const expected = [
    'CREATE TABLE IF NOT EXISTS public.template_health_history',
    "cron.schedule(",
    "'lcc-template-health-rollup'",
    "'0 6 * * 1'",
    "'/api/operations?_route=draft&action=health-rollup'",
    '"lookback_days": 120',
    '"persist": true',
  ];
  const missing = expected.filter(s => !src.includes(s));
  if (missing.length > 0) {
    throw new Error('Migration missing sentinels:\n  - ' + missing.join('\n  - '));
  }
  report.push(['LCC Opps R2-L-1 history table + cron', 0, 'verified ✓']);
}

async function verifyHandler(report) {
  const path = resolve(REPO_ROOT, 'api', 'operations.js');
  if (!await fileExists(path)) throw new Error('api/operations.js not found.');
  const src = await readFile(path, 'utf8');
  const expected = [
    "action === 'health-rollup'",
    'R2-L-1 (2026-05-19): weekly cron entry point',
    'template_health_history',
    "run_source: 'lcc-template-health-rollup'",
  ];
  const missing = expected.filter(s => !src.includes(s));
  if (missing.length > 0) {
    throw new Error(
      'api/operations.js missing R2-L-1 handler sentinels:\n  - ' +
      missing.join('\n  - ') +
      '\nHas the operations.js Python-via-bash edit been applied yet?'
    );
  }
  report.push(['api/operations.js (?action=health-rollup handler)', 0, 'verified ✓']);
}

async function updateRound2Findings(report) {
  const path = resolve(REPO_ROOT, 'audit', 'ROUND_2_FINDINGS_2026-05-19.md');
  if (!await fileExists(path)) throw new Error('ROUND_2_FINDINGS_2026-05-19.md not found.');
  const original = await readFile(path, 'utf8');
  const eol = detectEol(original);

  const sentinel = 'R2-L-1 closeout (2026-05-19)';
  if (original.includes(sentinel)) {
    report.push(['ROUND_2_FINDINGS_2026-05-19.md', 0, 'already applied']);
    return;
  }

  const block = toEol(`

## ${sentinel} — template health weekly rollup + history table 🟧 REVIEW
- **Branch:** \`audit/r2-l-1-template-health-weekly-cron\`
- **Patch:** \`audit/patches/R2-L-1-template-health-weekly-cron/apply.mjs\`
- **Migration:** \`supabase/migrations/20260519120000_lcc_r2_l1_template_health_history_and_cron.sql\`
- **Code change:** \`api/operations.js\` adds POST \`?_route=draft&action=health-rollup\` handler
- **Closes:** R2-L-1 (HIGH)

### Diagnosis
\`evaluateTemplateHealth()\` (api/_shared/template-refinement.js:41) is exposed
at \`/api/operations?_route=draft&action=health\` and the handler already
auto-flags templates that need revision. But no scheduled job calls it. The
weekly health report at reports/lcc-template-health-weekly-latest.md is
regenerated by hand; the loop has no time-series and no automated cadence.

### Fix
Two coordinated pieces:

1. **\`public.template_health_history\` table** (LCC Opps) — one row per
   rollup, captures the full structured evaluations payload as JSONB plus
   pre-rolled aggregates (template_count, evaluated_count,
   needs_revision_count, stale_count, total_sends, revisions_flagged,
   run_duration_ms). Indexed on \`recorded_at DESC\` for the "last 13 weeks
   trend" query and a partial index on rows with non-zero
   needs_revision_count so the daily briefing can flag week-over-week
   regressions in one cheap query.

2. **\`?_route=draft&action=health-rollup\` handler** — same evaluateTemplateHealth +
   flag-and-suggest pass as \`?action=health\`, plus persists a row to
   template_health_history. \`persist=false\` query param lets a UI dashboard
   tab call the endpoint without polluting the time-series. The cron always
   sets \`persist=true\`.

3. **pg_cron \`lcc-template-health-rollup\`** — every Monday 06:00 UTC,
   POSTs \`/api/operations?_route=draft&action=health-rollup\` with
   \`{"lookback_days": 120, "persist": true}\`. Calls go through
   \`public.lcc_cron_post('/api/...', payload, 'vercel')\` — same plumbing
   the other 8 LCC crons use.

### Why Monday 06:00 UTC
- Late enough that any Sunday-evening template_sends have already landed
  in template_sends.
- Early enough for the Monday-morning briefing to read the fresh rollup.
- 06:00 UTC = 01:00 ET / 22:00 PT Sunday — outside business hours
  everywhere.

### Sandbox tooling note
\`api/operations.js\` is 200 KB — under the QA-31 truncation threshold for
the Cowork Edit tool, but the first Edit attempt landed a truncated copy of
the file (missing the last 11 lines). Restored from \`git show HEAD\` and
re-applied via Python-via-bash with an explicit CRLF preservation step
(HEAD uses CRLF endings; LF write produced a 4,499-line whole-file diff).
Final \`git diff --stat\`: 74 insertions, 0 deletions. Clean.

### Verification (post-apply)

\`\`\`sql
-- On LCC Opps
\\d public.template_health_history
SELECT * FROM cron.job WHERE jobname = 'lcc-template-health-rollup';
-- Expected: 1 row, schedule='0 6 * * 1', active=true

-- Trigger a one-shot manual run
SELECT public.lcc_cron_post(
  '/api/operations?_route=draft&action=health-rollup',
  '{"lookback_days": 120, "persist": true}'::jsonb,
  'vercel'
);

-- Verify history row landed
SELECT recorded_at, template_count, evaluated_count, needs_revision_count, total_sends, run_duration_ms
  FROM public.template_health_history
 ORDER BY recorded_at DESC LIMIT 5;
\`\`\`

### Risks
- Today template_sends has zero rows over 120 days (D-3 hasn't shipped),
  so the first ~N weekly rollups will show \`total_sends=0\` and
  \`evaluated_count=0\`. That's the correct baseline; the trend table starts
  capturing the moment D-3's record_send flow lands.
- Auto-flag side effect: \`?action=health-rollup\` runs the same
  \`flagTemplateForRevision\` pass as \`?action=health\`. With
  \`total_sends=0\`, no template hits the EDIT_DISTANCE_FLAG_THRESHOLD
  (which requires hasEnoughData = sends ≥ MIN_SENDS_FOR_EVALUATION=5). So
  no false flags during the empty period.
- generateRevisionSuggestion (called for each needs_revision template)
  uses AI tokens. With no flagged templates today, cost is $0; once D-3
  ships, budget ~$0.10/week for the rollup based on observed flagged
  template counts.

### Out of scope (deferred follow-ups)
- **R2-L-1b: trend sparkline on Templates admin tab.** Read the last 13
  rollups from template_health_history; render per-template avg-edit-distance
  / reply-rate / deal-rate trends. Defer until the table has more than a
  few rows.
- **R2-L-1c: week-over-week regression alert in daily briefing.** When the
  current week's needs_revision_count exceeds last week's by >20%, surface
  in the strategic priorities section. Pair with the D-3 / template-sends
  flow.

### Files changed
- \`supabase/migrations/20260519120000_lcc_r2_l1_template_health_history_and_cron.sql\` (new)
- \`api/operations.js\` — added \`?action=health-rollup\` handler (74 lines)
- \`audit/patches/R2-L-1-template-health-weekly-cron/\` — patch package
- \`audit/ROUND_2_FINDINGS_2026-05-19.md\` — this closeout

No frontend. No Edge Function. No allowlist changes.
`, eol);

  const updated = original + block;
  const delta = updated.length - original.length;
  report.push(['ROUND_2_FINDINGS_2026-05-19.md (' + (eol === '\r\n' ? 'CRLF' : 'LF') + ')', delta, DRY ? 'dry-run' : 'written']);
  if (!DRY) await writeFile(path, updated, 'utf8');
}

async function main() {
  console.log('\n=== LCC R2-L-1 — template health weekly rollup + history ===');
  console.log('Mode: ' + (DRY ? 'DRY-RUN' : 'APPLY') + '\n');
  if (!await fileExists(resolve(REPO_ROOT, 'package.json'))) {
    throw new Error('Could not find package.json at ' + REPO_ROOT + '.');
  }
  const report = [];
  await verifyMigration(report);
  await verifyHandler(report);
  await updateRound2Findings(report);
  console.log('--- ' + (DRY ? 'DRY-RUN' : 'APPLY') + ' SUMMARY ---');
  for (const [file, delta, note] of report) {
    const sign = delta > 0 ? '+' : (delta < 0 ? '' : '±');
    console.log('  ' + file.padEnd(70) + '  ' + sign + delta + ' bytes  (' + note + ')');
  }
  if (DRY) console.log('\n✓ Dry-run complete. Re-run with --apply.\n');
  else     console.log('\n✓ Apply complete. Next: apply the .sql via Supabase MCP on LCC Opps.\n');
}
main().catch(err => { console.error('\n❌ FAILED: ' + err.message + '\n'); process.exit(1); });
