-- DEED1-reconcile (2026-09-15)
--
-- ⚠️ THIS FILE DOES NOT AUTHOR NEW BEHAVIOR. It is a RECONCILIATION migration that
-- records three objects a prior Cowork session (DEED1, filed 2026-09-15) applied
-- LIVE to Dialysis_DB (zqzrriwuavgrquhisnoa) without committing any migration file —
-- the "running but not merged" class this repo's own CLAUDE.md documents repeatedly
-- (GOVDUP1-a, gov CLAUDE.md §13 lock-incident writeup). A rebuild from this repo
-- would have silently dropped a table and restored two stale objects, re-admitting
-- the 4 bad owner-conflict rows DEED1 removed.
--
-- Every statement below was generated FROM THE LIVE OBJECTS
-- (pg_get_functiondef / pg_get_viewdef / information_schema), not retyped from
-- memory, because the word-boundary regexes in v_owner_source_conflict
-- (\mjll\M, \mbancorp\M, and the new leasing…finance clause) have escaping that
-- is ambiguous to hand-transcribe, and a silently wrong regex changes which rows
-- auto-fix. This migration changes NO behavior; every post-apply check below must
-- reproduce the DEED1 response numbers exactly.
--
-- Objects reconciled:
--   1. public.dia_owner_name_alias           (NEW TABLE — did not exist before DEED1)
--   2. public.dia_owner_share_significant_token(text,text)  (body now consults #1)
--   3. public.v_owner_source_conflict        (auto_fixable grantee-exclusion regex
--                                              gained `leasing\s*(?:and|&)\s*finance`)
--
-- Reversal: DROP VIEW public.v_owner_source_conflict (re-create the pre-DEED1 body
-- from git history); DROP FUNCTION public.dia_owner_share_significant_token(text,text)
-- (re-create without the alias-table EXISTS clause); DROP TABLE public.dia_owner_name_alias.
--
-- ⚠️ DEED1-reconcile-2 (2026-09-16, Cowork): this file originally landed in the
-- Dialysis repo (PR #7412), which does not own Dialysis_DB's schema objects per
-- this repo's own ownership doctrine (see CLAUDE.md "ONE REPO OWNS EACH
-- DATABASE'S OBJECTS" + supabase/migrations/dialysis/README.md). Ported here
-- verbatim, byte-identical to what was applied live — not re-derived. Re-verified
-- against Dialysis_DB before the port: md5(pg_get_viewdef('v_owner_source_conflict'))
-- = 9fc5aa3f824b125853b3ac8c8a8388f1 (4747 chars); md5(pg_get_functiondef(
-- 'dia_owner_share_significant_token(text,text)')) = 72b48cd949db4de5502812920b2e5dd0
-- (2183 chars). Both match the pre-port pin exactly — no live drift occurred
-- between the two rounds.

-- ---------------------------------------------------------------------------
-- 1. dia_owner_name_alias — curated, human-confirmed name-token pairings.
--    Each row asserts that alias_token and canonical_token name the SAME party
--    even though they share no substring. This is NOT an inference table — do
--    not populate it with anything the comparator could derive on its own, and
--    do not add a row without a human confirming the pairing (see `notes`).
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.dia_owner_name_alias (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alias_token     text NOT NULL,
    canonical_token text NOT NULL,
    notes           text,
    created_at      timestamptz NOT NULL DEFAULT now(),
    UNIQUE (alias_token, canonical_token)
);

INSERT INTO public.dia_owner_name_alias (alias_token, canonical_token, notes)
VALUES (
    'smfg',
    'sumitomo',
    'DEED1 2026-09-15: SMFG = Sumitomo Mitsui Financial Group, the abbreviated grantee name recorded on deeds for "Sumitomo Bank Leasing And Finance Inc" (dia properties 23902, 27709, 23997, 29757, 36358, 3776967, 27845, 3453603). No shared token exists between the strings, so dia_owner_share_significant_token() could not see this without an explicit entry. Human-confirmed pairing, not inferred.'
)
ON CONFLICT (alias_token, canonical_token) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 2. dia_owner_share_significant_token — comparator gains an OR-branch that
--    checks the curated alias table when the generic-token-stoplist check
--    (unchanged) finds nothing shared.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.dia_owner_share_significant_token(a text, b text)
 RETURNS boolean
 LANGUAGE sql
 STABLE
 SET search_path TO 'public', 'extensions', 'pg_temp'
AS $function$
  WITH ta AS (
    SELECT DISTINCT t FROM unnest(regexp_split_to_array(lower(coalesce(a,'')), '[^a-z0-9]+')) AS t
    WHERE length(t) >= 4 AND NOT t = ANY (ARRAY[
        'company','companies','corp','corporation','limited','incorporated','trust','trusts','fund','funds','holding','holdings','holdco',
        'partner','partners','partnership','properties','property','propco','realty','estate','real','capital','group','associates','associate',
        'investment','investments','management','development','developments','developers','center','centers','centre','plaza','building','buildings',
        'tower','towers','family','foundation','enterprises','ventures','venture','government','federal','authority','national','owner','owners',
        'acquisition','acquisitions','income','equities','equity']::text[])
  ), tb AS (
    SELECT DISTINCT t FROM unnest(regexp_split_to_array(lower(coalesce(b,'')), '[^a-z0-9]+')) AS t
    WHERE length(t) >= 4 AND NOT t = ANY (ARRAY[
        'company','companies','corp','corporation','limited','incorporated','trust','trusts','fund','funds','holding','holdings','holdco',
        'partner','partners','partnership','properties','property','propco','realty','estate','real','capital','group','associates','associate',
        'investment','investments','management','development','developments','developers','center','centers','centre','plaza','building','buildings',
        'tower','towers','family','foundation','enterprises','ventures','venture','government','federal','authority','national','owner','owners',
        'acquisition','acquisitions','income','equities','equity']::text[])
  )
  SELECT EXISTS (SELECT 1 FROM ta JOIN tb USING (t))
      OR EXISTS (
           SELECT 1 FROM public.dia_owner_name_alias al
           WHERE (al.alias_token IN (SELECT t FROM ta) AND al.canonical_token IN (SELECT t FROM tb))
              OR (al.alias_token IN (SELECT t FROM tb) AND al.canonical_token IN (SELECT t FROM ta))
         );
$function$;

-- ---------------------------------------------------------------------------
-- 3. v_owner_source_conflict — the auto_fixable grantee exclusion regex gains
--    a `leasing (and|&) finance` clause (financing-instrument grantee, not an
--    owner-of-record). Everything else in the view is unchanged from the
--    pre-DEED1 body.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE VIEW public.v_owner_source_conflict AS
 WITH base AS (
         SELECT p.property_id,
            p.recorded_owner_id,
            COALESCE(p.recorded_owner_name, ro.name) AS recorded_owner_name,
            p.latest_deed_grantee,
            p.latest_deed_date,
            COALESCE(p.true_owner_name, to2.name) AS true_owner_name,
            NULL::numeric AS annual_rent,
            p.address,
            p.city,
            p.state,
            lower(regexp_replace(COALESCE(COALESCE(p.recorded_owner_name, ro.name), ''::text), '[^a-z0-9]'::text, ''::text, 'gi'::text)) AS ro_norm,
            lower(regexp_replace(p.latest_deed_grantee, '[^a-z0-9]'::text, ''::text, 'gi'::text)) AS grantee_norm,
            lower(regexp_replace(COALESCE(COALESCE(p.true_owner_name, to2.name), ''::text), '[^a-z0-9]'::text, ''::text, 'gi'::text)) AS to_norm
           FROM properties p
             LEFT JOIN recorded_owners ro ON ro.recorded_owner_id = p.recorded_owner_id
             LEFT JOIN true_owners to2 ON to2.true_owner_id = p.true_owner_id
          WHERE p.latest_deed_grantee IS NOT NULL AND COALESCE(p.recorded_owner_name, ro.name) IS NOT NULL
        ), flagged AS (
         SELECT b.property_id,
            b.recorded_owner_id,
            b.recorded_owner_name,
            b.latest_deed_grantee,
            b.latest_deed_date,
            b.true_owner_name,
            b.annual_rent,
            b.address,
            b.city,
            b.state,
            b.ro_norm,
            b.grantee_norm,
            b.to_norm,
            b.recorded_owner_name ~* '(cushman|wakefield|c&w|colliers|cbre|newmark|\mjll\M|marcus\s*&?\s*millichap|\mm&m\M|\mmmi\M|institutional property advisors|\mipa\M|\msrs\M|avison young|\mnai\M|matthews|\msvn\M|keller williams|flagship|northmarq)'::text AS is_broker_owner,
            b.latest_deed_grantee !~* '(cushman|wakefield|c&w|colliers|cbre|newmark|\mjll\M|marcus\s*&?\s*millichap|\mm&m\M|\mmmi\M|institutional property advisors|\mipa\M|\msrs\M|avison young|\may\M|\mnai\M|matthews|flagship|\msvn\M|keller williams|\mkw\M)'::text AND b.latest_deed_grantee !~* '^\s*(u\s?\.?\s?s\s?\.?\s?a|united states|gsa|government|federal|n\.?/?a|unknown|none|tbd)\b'::text AND length(regexp_replace(b.latest_deed_grantee, '[^a-z0-9]'::text, ''::text, 'gi'::text)) >= 4 AND b.latest_deed_grantee ~ '[A-Za-z]'::text AS grantee_passes_guards,
            (EXISTS ( SELECT 1
                   FROM sales_transactions st
                  WHERE st.property_id = b.property_id AND lower(regexp_replace(COALESCE(st.seller_name, ''::character varying)::text, '[^a-z0-9]'::text, ''::text, 'gi'::text)) = b.ro_norm AND lower(regexp_replace(COALESCE(st.buyer_name, ''::character varying)::text, '[^a-z0-9]'::text, ''::text, 'gi'::text)) = b.grantee_norm)) AS is_stale_seller
           FROM base b
          WHERE b.ro_norm IS DISTINCT FROM b.grantee_norm
        ), kinded AS (
         SELECT f.property_id,
            f.recorded_owner_id,
            f.recorded_owner_name,
            f.latest_deed_grantee,
            f.latest_deed_date,
            f.true_owner_name,
            f.annual_rent,
            f.address,
            f.city,
            f.state,
            f.is_broker_owner,
            f.grantee_passes_guards,
            f.is_stale_seller,
                CASE
                    WHEN f.is_broker_owner THEN 'broker_as_owner'::text
                    WHEN f.to_norm <> ''::text AND f.ro_norm = f.to_norm THEN 'spe_vs_parent'::text
                    WHEN f.is_stale_seller THEN 'stale_seller'::text
                    ELSE 'deed_newer_stale'::text
                END AS conflict_kind
           FROM flagged f
        )
 SELECT 'dia'::text AS domain,
    kinded.property_id,
    kinded.recorded_owner_id,
    kinded.recorded_owner_name,
    kinded.latest_deed_grantee,
    kinded.latest_deed_date,
    kinded.true_owner_name,
    kinded.annual_rent,
    kinded.address,
    kinded.city,
    kinded.state,
    kinded.is_broker_owner,
    kinded.grantee_passes_guards,
    kinded.conflict_kind,
    ((kinded.conflict_kind = ANY (ARRAY['broker_as_owner'::text, 'stale_seller'::text])) OR kinded.conflict_kind = 'deed_newer_stale'::text AND kinded.latest_deed_date IS NOT NULL AND kinded.latest_deed_date >= (CURRENT_DATE - '2 years'::interval) AND NOT dia_owner_share_significant_token(kinded.recorded_owner_name, kinded.latest_deed_grantee)) AND kinded.grantee_passes_guards AND kinded.conflict_kind <> 'spe_vs_parent'::text AND NOT kinded.latest_deed_grantee ~* '(\mmortgage\M|deed of trust|mortgage finance|home loans?|savings bank|banking corp(oration)?|\mbancorp\M|financial corp|\mfsb\M|leasing\s*(?:and|&)\s*finance)'::text AS auto_fixable
   FROM kinded;
