-- MERGE1 — dia_merge_property: FOLD on collision instead of losing the child row.
--
-- Measured live 2026-09-05 (dia_property_merge_backup, 585 merges / 206 collisions):
--   property_embeddings.property_id_error           198  (UNIQUE(property_id) — re-derivable)
--   cap_rate_history.property_id_error                23  (UNIQUE(property_id,event_type,event_date) —
--                                                          substantive point-in-time value history)
--   property_metadata_backfill_queue.property_id_error 11 (UNIQUE(property_id) — queue state)
--   pending_updates.property_id_error                  1  (PARTIAL UNIQUE ... WHERE status='pending_review')
--
-- The generic properties-FK loop in dia_merge_property used to catch the unique_violation, record it
-- under "<table>.<col>_error", and leave the row pointing at drop_id — which is then silently destroyed
-- by ON DELETE CASCADE when properties.property_id = drop_id is deleted a few lines later. The backup
-- table's snapshotted child id then points at nothing, so dia_unmerge_property reports it "restored" or
-- honestly "_lost" while the data is gone either way.
--
-- Fix: every properties-FK table gets a POLICY (re_derivable / fold_fill_blanks / resolve_status).
-- On a real collision the row is never blind-deleted:
--   - re_derivable     -> the drop-side row is discarded and the discard is recorded as NOT a loss
--                         (the value is recomputed by an existing worker; keep-side row is authoritative).
--   - resolve_status   -> the drop-side row's status is flipped out of the partial-unique predicate's
--                         scope, then repointed to keep_id UNCHANGED otherwise — the row survives.
--   - fold_fill_blanks -> the drop-side row is located against its matching keep-side row (via the
--                         conflicting unique key), every column that is NULL on the keep row is filled
--                         from the drop row (COALESCE, never overwrites a keep-side value), then the
--                         drop row is deleted. The keep row now carries the union of both sides.
--   - (no policy row)  -> defaults to fold_fill_blanks off the table's own single-column PK, so an
--                         UNCLASSIFIED table is never blind-deleted either.
--
-- Discipline: additive, reversible (re-create the prior function bodies), no data mutated by this
-- migration itself — it changes behaviour for merges run AFTER this ships. The 206 historical
-- collisions are NOT touched; they are recorded in docs/audits/MERGE1_PROPERTY_MERGE_COLLISION_FOLD.md.

CREATE TABLE IF NOT EXISTS public.dia_merge_child_policy (
  table_name      text PRIMARY KEY,
  policy          text NOT NULL CHECK (policy IN ('re_derivable','fold_fill_blanks','resolve_status')),
  pk_col          text NOT NULL,
  conflict_cols   text[] NOT NULL DEFAULT '{}',
  resolve_column  text,
  resolve_value   text,
  notes           text,
  created_at      timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.dia_merge_child_policy IS
  'MERGE1: per-table fold policy consulted by dia_merge_fold_table() on a properties-FK repoint '
  'collision inside dia_merge_property(). A table with no row here defaults to fold_fill_blanks '
  'off its own single-column PK -- never a blind delete.';

INSERT INTO public.dia_merge_child_policy (table_name, policy, pk_col, conflict_cols, notes) VALUES
  ('property_embeddings', 're_derivable', 'property_id', ARRAY['property_id'],
   'Embedding is derived from the property''s own text and is regenerated by the embedding refresh '
   'worker. The drop-side embedding is discarded as RE-DERIVABLE, not counted as a loss.'),
  ('cap_rate_history', 'fold_fill_blanks', 'id', ARRAY['property_id','event_type','event_date'],
   'Substantive point-in-time value/expense-anchor history (see CLAUDE.md sec 12). A collision means '
   'the SAME (property,event_type,event_date) was recorded from both sides -- fold fills any blank on '
   'the keep row from the drop row rather than destroying either observation.'),
  ('property_metadata_backfill_queue', 'fold_fill_blanks', 'queue_id', ARRAY['property_id'],
   'Queue state (missing_fields/attempts/last_attempt_at/last_error). Folded so a drop-side attempt '
   'history is not silently lost -- the keep-side queue row absorbs whatever the drop side observed.')
ON CONFLICT (table_name) DO NOTHING;

INSERT INTO public.dia_merge_child_policy
  (table_name, policy, pk_col, conflict_cols, resolve_column, resolve_value, notes) VALUES
  ('pending_updates', 'resolve_status', 'id', ARRAY['property_id','field_name','reason'],
   'status', 'superseded_by_merge',
   'pending_updates_unique_prop is a PARTIAL unique index scoped to status=''pending_review''. '
   'Flipping the drop-side row''s status out of that scope and THEN repointing it preserves the row '
   '(and its queue history) instead of destroying it. Known gap: dia_unmerge_property repoints the row '
   'back on reversal but does not restore the original status -- stated, not silently claimed.')
ON CONFLICT (table_name) DO NOTHING;

-- Fold one already-identified colliding row: locate its match on the keep side via the policy's
-- conflict key, fill every NULL keep-side column from the drop row, delete the drop row.
CREATE OR REPLACE FUNCTION public._dia_merge_fold_one_row(
  p_table text, p_fk_col text, p_pk_col text, p_conflict_cols text[],
  p_keep_id integer, p_drop_pk text
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_keep_pk text;
  v_where_parts text[] := ARRAY[]::text[];
  v_col text;
  v_set_parts text[] := ARRAY[]::text[];
  v_n_cols int;
BEGIN
  -- The keep-side row is identified by its FK column equalling keep_id (NOT by its own PK, which
  -- may be an unrelated surrogate id -- e.g. cap_rate_history.id vs property_id) plus every other
  -- conflict-key column matching the drop row.
  v_where_parts := ARRAY[format('k.%I = $1', p_fk_col)];
  FOREACH v_col IN ARRAY p_conflict_cols LOOP
    IF v_col <> p_fk_col THEN
      v_where_parts := v_where_parts || format('k.%I IS NOT DISTINCT FROM d.%I', v_col, v_col);
    END IF;
  END LOOP;

  EXECUTE format(
    'SELECT k.%I::text FROM public.%I k JOIN public.%I d ON %s WHERE d.%I::text = $2',
    p_pk_col, p_table, p_table, array_to_string(v_where_parts, ' AND '), p_pk_col
  ) INTO v_keep_pk USING p_keep_id, p_drop_pk;

  IF v_keep_pk IS NULL THEN
    -- No matching keep-side row for this conflict key -- the earlier violation must have been on a
    -- different row. Leave the drop row untouched rather than guess.
    RETURN jsonb_build_object('fold', 'no_matching_keep_row_found', 'drop_pk', p_drop_pk);
  END IF;

  FOR v_col IN
    SELECT column_name FROM information_schema.columns
     WHERE table_schema = 'public' AND table_name = p_table
       AND column_name NOT IN (p_pk_col, p_fk_col)
       AND column_name <> ALL(p_conflict_cols)
  LOOP
    v_set_parts := v_set_parts || format('%I = COALESCE(k.%I, d.%I)', v_col, v_col, v_col);
  END LOOP;
  v_n_cols := COALESCE(array_length(v_set_parts,1), 0);

  IF v_n_cols > 0 THEN
    EXECUTE format(
      'UPDATE public.%I k SET %s FROM public.%I d WHERE k.%I::text = $1 AND d.%I::text = $2',
      p_table, array_to_string(v_set_parts, ', '), p_table, p_pk_col, p_pk_col
    ) USING v_keep_pk, p_drop_pk;
  END IF;

  EXECUTE format('DELETE FROM public.%I WHERE %I::text = $1', p_table, p_pk_col) USING p_drop_pk;

  RETURN jsonb_build_object('fold', 'filled_blanks', 'keep_pk', v_keep_pk, 'drop_pk', p_drop_pk,
    'columns_considered', v_n_cols);
END;
$function$;

-- Per-table dispatcher, called from dia_merge_property's properties-FK loop ONLY on unique_violation.
CREATE OR REPLACE FUNCTION public.dia_merge_fold_table(
  p_table text, p_fk_col text, p_keep_id integer, p_drop_id integer
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_policy text; v_pk_col text; v_conflict_cols text[];
  v_resolve_column text; v_resolve_value text;
  v_row record; v_fold_detail jsonb;
  v_repointed int := 0; v_folded int := 0; v_discarded int := 0; v_resolved int := 0;
BEGIN
  SELECT policy, pk_col, conflict_cols, resolve_column, resolve_value
    INTO v_policy, v_pk_col, v_conflict_cols, v_resolve_column, v_resolve_value
  FROM public.dia_merge_child_policy WHERE table_name = p_table;

  IF v_policy IS NULL THEN
    -- Unclassified table: never blind-delete. Default to fold_fill_blanks off its own single-column PK.
    SELECT CASE WHEN count(*) = 1 THEN max(a.attname) ELSE NULL END INTO v_pk_col
    FROM pg_index i JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = ANY(i.indkey)
    WHERE i.indrelid = format('public.%I', p_table)::regclass AND i.indisprimary;
    IF v_pk_col IS NULL THEN
      RETURN jsonb_build_object('policy', 'unclassified_no_single_col_pk', 'held', true,
        'note', 'no dia_merge_child_policy row and no single-column PK -- left pointing at drop_id, '
                 'will NOT be auto-deleted by this function; register a policy row before merging this pair');
    END IF;
    v_policy := 'fold_fill_blanks';
    v_conflict_cols := ARRAY[p_fk_col];
  END IF;

  FOR v_row IN EXECUTE format('SELECT %I::text AS pk FROM public.%I WHERE %I = $1', v_pk_col, p_table, p_fk_col)
               USING p_drop_id
  LOOP
    BEGIN
      EXECUTE format('UPDATE public.%I SET %I = $1 WHERE %I::text = $2', p_table, p_fk_col, v_pk_col)
        USING p_keep_id, v_row.pk;
      v_repointed := v_repointed + 1;
    EXCEPTION WHEN unique_violation THEN
      IF v_policy = 'resolve_status' AND v_resolve_column IS NOT NULL THEN
        BEGIN
          EXECUTE format('UPDATE public.%I SET %I = $1 WHERE %I::text = $2', p_table, v_resolve_column, v_pk_col)
            USING v_resolve_value, v_row.pk;
          EXECUTE format('UPDATE public.%I SET %I = $1 WHERE %I::text = $2', p_table, p_fk_col, v_pk_col)
            USING p_keep_id, v_row.pk;
          v_resolved := v_resolved + 1;
        EXCEPTION WHEN unique_violation THEN
          v_fold_detail := public._dia_merge_fold_one_row(p_table, p_fk_col, v_pk_col, v_conflict_cols, p_keep_id, v_row.pk);
          v_folded := v_folded + 1;
        END;
      ELSIF v_policy = 're_derivable' THEN
        EXECUTE format('DELETE FROM public.%I WHERE %I::text = $1', p_table, v_pk_col) USING v_row.pk;
        v_discarded := v_discarded + 1;
      ELSE
        v_fold_detail := public._dia_merge_fold_one_row(p_table, p_fk_col, v_pk_col, v_conflict_cols, p_keep_id, v_row.pk);
        v_folded := v_folded + 1;
      END IF;
    END;
  END LOOP;

  RETURN jsonb_build_object('policy', v_policy, 'repointed', v_repointed, 'folded', v_folded,
    'discarded_re_derivable', v_discarded, 'resolved_in_place', v_resolved);
END;
$function$;

-- dia_merge_property itself: the properties-FK loop now routes a unique_violation through
-- dia_merge_fold_table() instead of leaving the row pointing at drop_id (where it dies to CASCADE).
CREATE OR REPLACE FUNCTION public.dia_merge_property(p_keep_id integer, p_drop_id integer)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_rewired jsonb := '{}'::jsonb; v_n integer; v_record record; v_cnt integer;
  v_sid integer; v_keep_sale integer; v_fk record;
  v_rep integer := 0; v_drp integer := 0; v_setnull integer := 0; v_children_repointed integer := 0;
  v_fold_detail jsonb;
BEGIN
  IF p_keep_id IS NULL OR p_drop_id IS NULL THEN RAISE EXCEPTION 'dia_merge_property: keep_id and drop_id must both be non-null'; END IF;
  IF p_keep_id = p_drop_id THEN RAISE EXCEPTION 'dia_merge_property: keep_id and drop_id must differ (got %)', p_keep_id; END IF;
  IF NOT EXISTS (SELECT 1 FROM public.properties WHERE property_id = p_keep_id) THEN RAISE EXCEPTION 'dia_merge_property: keep_id % not found in properties', p_keep_id; END IF;
  IF NOT EXISTS (SELECT 1 FROM public.properties WHERE property_id = p_drop_id) THEN RAISE EXCEPTION 'dia_merge_property: drop_id % not found in properties', p_drop_id; END IF;

  CREATE TEMP TABLE IF NOT EXISTS _mg_lease (id integer) ON COMMIT DROP;
  TRUNCATE _mg_lease;
  INSERT INTO _mg_lease SELECT ld.lease_id FROM public.leases ld
   WHERE ld.property_id = p_drop_id AND ld.tenant_id IS NOT NULL AND ld.lease_start IS NOT NULL AND ld.lease_expiration IS NOT NULL
     AND EXISTS (SELECT 1 FROM public.leases lk WHERE lk.property_id=p_keep_id AND lk.tenant_id=ld.tenant_id AND lk.lease_start=ld.lease_start AND lk.lease_expiration=ld.lease_expiration);
  IF EXISTS (SELECT 1 FROM _mg_lease) THEN
    DELETE FROM public.lease_escalations WHERE lease_id IN (SELECT id FROM _mg_lease);
    DELETE FROM public.expenses WHERE lease_id IN (SELECT id FROM _mg_lease);
    DELETE FROM public.leases WHERE lease_id IN (SELECT id FROM _mg_lease);
    GET DIAGNOSTICS v_cnt = ROW_COUNT; v_rewired := v_rewired || jsonb_build_object('leases_dedup_dropped', v_cnt);
  END IF;

  IF EXISTS (SELECT 1 FROM public.available_listings WHERE property_id=p_keep_id AND is_active IS TRUE) THEN
    DELETE FROM public.broker_market_coverage WHERE listing_id IN (SELECT listing_id FROM public.available_listings WHERE property_id=p_drop_id AND is_active IS TRUE);
    DELETE FROM public.available_listings WHERE property_id=p_drop_id AND is_active IS TRUE;
    GET DIAGNOSTICS v_cnt = ROW_COUNT;
    IF v_cnt > 0 THEN v_rewired := v_rewired || jsonb_build_object('active_listings_dedup_dropped', v_cnt); END IF;
  END IF;

  FOR v_sid IN SELECT sale_id FROM public.sales_transactions WHERE property_id = p_drop_id LOOP
    BEGIN
      UPDATE public.sales_transactions SET property_id = p_keep_id WHERE sale_id = v_sid;
      v_rep := v_rep + 1;
    EXCEPTION WHEN unique_violation THEN
      BEGIN
        SELECT k.sale_id INTO v_keep_sale FROM public.sales_transactions d
          JOIN public.sales_transactions k ON k.property_id = p_keep_id
           AND k.sale_date IS NOT DISTINCT FROM d.sale_date AND COALESCE(k.sold_price, -1) = COALESCE(d.sold_price, -1)
         WHERE d.sale_id = v_sid ORDER BY k.sale_id LIMIT 1;
        IF v_keep_sale IS NOT NULL THEN
          FOR v_fk IN SELECT t.relname AS tbl, a.attname AS col FROM pg_constraint c
              JOIN pg_class t ON t.oid=c.conrelid JOIN pg_namespace n ON n.oid=t.relnamespace
              JOIN pg_attribute a ON a.attrelid=c.conrelid AND a.attnum=ANY(c.conkey)
             WHERE c.contype='f' AND c.confrelid='public.sales_transactions'::regclass AND n.nspname='public'
          LOOP
            BEGIN
              EXECUTE format('UPDATE public.%I SET %I = $1 WHERE %I = $2', v_fk.tbl, v_fk.col, v_fk.col) USING v_keep_sale, v_sid;
              GET DIAGNOSTICS v_n = ROW_COUNT; v_children_repointed := v_children_repointed + v_n;
            EXCEPTION WHEN OTHERS THEN NULL; END;
          END LOOP;
        END IF;
        DELETE FROM public.sales_transactions WHERE sale_id = v_sid;
        v_drp := v_drp + 1;
        IF v_keep_sale IS NULL THEN v_setnull := v_setnull + 1; END IF;
      EXCEPTION WHEN OTHERS THEN
        v_rewired := v_rewired || jsonb_build_object('sales_transactions.sale_id_delete_failed:' || v_sid::text, SQLERRM);
      END;
      v_keep_sale := NULL;
    END;
  END LOOP;
  IF (v_rep + v_drp) > 0 THEN
    v_rewired := v_rewired || jsonb_build_object('sales_repointed', v_rep, 'sales_dedup_dropped', v_drp,
      'sale_children_repointed', v_children_repointed, 'sales_dropped_children_setnull', v_setnull);
  END IF;

  DELETE FROM public.property_public_records d WHERE d.property_id = p_drop_id
     AND EXISTS (SELECT 1 FROM public.property_public_records k WHERE k.property_id=p_keep_id
                  AND k.record_type IS NOT DISTINCT FROM d.record_type AND k.record_id IS NOT DISTINCT FROM d.record_id);
  GET DIAGNOSTICS v_cnt = ROW_COUNT;
  IF v_cnt > 0 THEN v_rewired := v_rewired || jsonb_build_object('public_records_dedup_dropped', v_cnt); END IF;

  DECLARE v_oh bigint;
  BEGIN
    FOR v_oh IN SELECT ownership_id FROM public.ownership_history WHERE property_id = p_drop_id LOOP
      BEGIN UPDATE public.ownership_history SET property_id = p_keep_id WHERE ownership_id = v_oh;
      EXCEPTION WHEN unique_violation OR exclusion_violation THEN DELETE FROM public.ownership_history WHERE ownership_id = v_oh; END;
    END LOOP;
  END;

  DECLARE v_pse bigint;
  BEGIN
    FOR v_pse IN SELECT sale_event_id FROM public.property_sale_events WHERE property_id = p_drop_id LOOP
      BEGIN UPDATE public.property_sale_events SET property_id = p_keep_id WHERE sale_event_id = v_pse;
      EXCEPTION WHEN unique_violation OR exclusion_violation THEN DELETE FROM public.property_sale_events WHERE sale_event_id = v_pse; END;
    END LOOP;
  END;

  FOR v_record IN SELECT n.nspname AS schemaname, t.relname AS tablename, a.attname AS colname FROM pg_constraint c
      JOIN pg_class t ON t.oid=c.conrelid JOIN pg_namespace n ON n.oid=t.relnamespace
      JOIN pg_attribute a ON a.attrelid=c.conrelid AND a.attnum=ANY(c.conkey)
     WHERE c.contype='f' AND c.confrelid='public.properties'::regclass AND n.nspname='public' ORDER BY t.relname, a.attname
  LOOP
    BEGIN
      EXECUTE format('UPDATE %I.%I SET %I = $1 WHERE %I = $2', v_record.schemaname, v_record.tablename, v_record.colname, v_record.colname) USING p_keep_id, p_drop_id;
      GET DIAGNOSTICS v_n = ROW_COUNT;
      IF v_n > 0 THEN v_rewired := v_rewired || jsonb_build_object(v_record.tablename || '.' || v_record.colname, v_n); END IF;
    EXCEPTION WHEN unique_violation THEN
      v_fold_detail := public.dia_merge_fold_table(v_record.tablename, v_record.colname, p_keep_id, p_drop_id);
      v_rewired := v_rewired || jsonb_build_object(v_record.tablename || '.' || v_record.colname, v_fold_detail);
    WHEN OTHERS THEN
      v_rewired := v_rewired || jsonb_build_object(v_record.tablename || '.' || v_record.colname || '_error', SQLERRM);
    END;
  END LOOP;

  BEGIN
    DELETE FROM public.properties WHERE property_id = p_drop_id;
    GET DIAGNOSTICS v_n = ROW_COUNT;
  EXCEPTION WHEN OTHERS THEN
    v_n := 0; v_rewired := v_rewired || jsonb_build_object('properties_delete_failed', SQLERRM);
  END;
  v_rewired := v_rewired || jsonb_build_object('properties_deleted', v_n);

  RETURN jsonb_build_object('keep_id', p_keep_id, 'drop_id', p_drop_id, 'rewired', v_rewired,
    'merge_function_version', 'dia_merge1_fold_on_collision_2026_09_05');
END;
$function$;
