-- ============================================================================
-- R58 "Unit 4" — CRE doc-text sidecar + BOV extraction record
-- Project: LCC Opps (xengecqvemvfknjvbvrq)
--
-- Two ADDITIVE tables (no change to any existing table/data):
--
--   1. lcc_cre_property_document_text  — the raw_text SIDECAR.
--        OCR/text-extract runs ONCE per document (Unit 1) and lands here; every
--        consumer (Unit 4, comps, OM build, any access point) reuses it instead
--        of re-OCRing at the access point. Hangs off lcc_cre_property_documents
--        the way staged_intake_extractions hangs off intake_id — the registry
--        stays a registry.
--
--   2. lcc_cre_bov_extraction          — the reviewable Unit-4 RECORD.
--        One row per (cre_property_id, extractor_version): the property's lease/
--        dd/om text turned into the BOV generator's Pydantic shape (property,
--        tenants[] w/ abstract+rent_schedule+credit+clause_refs, real_estate,
--        underwriting_hints). The BOV generator's {cre_property_id} input path
--        loads the latest status='reviewed' (fallback 'extracted') row and builds
--        the identical BOVRequest — so "BOV this property" from any surface yields
--        the same workbook because the lease data is ONE extracted record.
--
-- RLS: enabled with NO policies, matching lcc_cre_property_documents — access is
-- service-key-only via opsQuery (the anon/authed roles see nothing).
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. raw_text sidecar
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.lcc_cre_property_document_text (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id       bigint NOT NULL
                      REFERENCES public.lcc_cre_property_documents(id) ON DELETE CASCADE,
  cre_property_id   bigint,                 -- denormalized for cheap per-property gather
  document_type     text,                   -- copied from the registry row at extract time
  raw_text          text,
  method            text,                   -- 'pdf_text' | 'text_decode' | 'binary_decode' | 'ocr'
  ocr_tier          text,                   -- 'free' | 'free_low_conf' | 'cloud_cheap' | 'cloud'
  ocr_engine        text,
  ocr_confidence    numeric,                -- 0-100 (free / cheap-cloud); null for gpt-4o
  ocr_pages         int,                    -- per-page cost telemetry (DocAI bills per page)
  page_count        int,
  pages             jsonb,                  -- [{page:int, text:string}] from the DocAI layout tier
  thin_text_layer   boolean DEFAULT false,  -- true when the digital text layer was junk → OCR'd
  char_len          int,
  needs_ocr         boolean DEFAULT false,  -- terminal-this-pass: scanned + no OCR available
  reason            text,                   -- when needs_ocr / failed
  extractor_version text NOT NULL DEFAULT 'unit1_v1',
  extracted_at      timestamptz NOT NULL DEFAULT now()
);

-- One sidecar per (document, extractor_version) — the idempotency key the worker
-- upserts on so re-running a tick never duplicates or re-OCRs a filled row.
CREATE UNIQUE INDEX IF NOT EXISTS ux_cre_doc_text_doc_ver
  ON public.lcc_cre_property_document_text (document_id, extractor_version);

CREATE INDEX IF NOT EXISTS ix_cre_doc_text_property
  ON public.lcc_cre_property_document_text (cre_property_id);

CREATE INDEX IF NOT EXISTS ix_cre_doc_text_needs_ocr
  ON public.lcc_cre_property_document_text (needs_ocr) WHERE needs_ocr;

ALTER TABLE public.lcc_cre_property_document_text ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.lcc_cre_property_document_text IS
  'R58 Unit 4 (2A): raw_text sidecar for lcc_cre_property_documents. OCR/text runs ONCE per doc (Unit 1) and every consumer reads this. Service-key access only.';

-- ---------------------------------------------------------------------------
-- 2. Unit-4 BOV extraction record
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.lcc_cre_bov_extraction (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cre_property_id   bigint NOT NULL
                      REFERENCES public.lcc_cre_properties(id) ON DELETE CASCADE,
  -- The BOV generator payload: { property, tenants[], real_estate, underwriting_hints }
  -- shaped to bov-generator/main.py's Pydantic schema. Reviewable in the
  -- live-ingest UI like every other extraction.
  record            jsonb NOT NULL,
  status            text NOT NULL DEFAULT 'extracted',  -- 'extracted' | 'reviewed' | 'rejected'
  -- Provenance / quality flags surfaced in the review UI.
  source_document_ids bigint[],                          -- registry ids that fed this record
  citation_risk     boolean DEFAULT false,               -- any low-confidence OCR in the chain
  ocr_confidence    numeric,                             -- min confidence across the source sidecars
  tenant_count      int,
  extractor_version text NOT NULL DEFAULT 'unit4_v1',
  extracted_at      timestamptz NOT NULL DEFAULT now(),
  reviewed_at       timestamptz,
  reviewed_by       text
);

-- One record per (property, extractor_version). A re-extract UPSERTs (merge) so
-- the latest run for a version replaces the prior one; older versions are kept
-- for audit. The generator selects newest reviewed, then newest extracted.
CREATE UNIQUE INDEX IF NOT EXISTS ux_cre_bov_extract_prop_ver
  ON public.lcc_cre_bov_extraction (cre_property_id, extractor_version);

CREATE INDEX IF NOT EXISTS ix_cre_bov_extract_prop_status
  ON public.lcc_cre_bov_extraction (cre_property_id, status);

ALTER TABLE public.lcc_cre_bov_extraction ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.lcc_cre_bov_extraction IS
  'R58 Unit 4 (2B): reviewable BOV record (bov-generator Pydantic shape) built from a property''s lease/dd/om text sidecars. The generator {cre_property_id} path loads the latest reviewed row. Service-key access only.';
