-- ============================================================================
-- LCC Opps — Round 2 finding R2-L-1 (2026-05-19):
-- Schedule weekly template-health rollup + persist results to a history table
--
-- Round 2 audit caught that `evaluateTemplateHealth()` (api/_shared/template-
-- refinement.js) is wired and exposed at /api/operations?_route=draft
-- &action=health, but no scheduled job calls it. The weekly health report at
-- reports/lcc-template-health-weekly-latest.md is regenerated by hand. Even
-- if a daily-briefing reads the live report, there is no time-series — no way
-- to ask "did template T-005's avg edit distance trend up after we tweaked
-- it?"
--
-- This migration:
--
--   1. Creates public.template_health_history — append-only, one row per
--      cron run, holding the structured report payload as JSONB so we can
--      query trends without joining 14+ per-template normalized rows.
--
--   2. Schedules pg_cron `lcc-template-health-rollup` every Monday 06:00 UTC.
--      Calls /api/operations?_route=draft&action=health-rollup via the
--      standard public.lcc_cron_post helper. The handler persists a row and
--      returns the same payload as ?action=health.
--
--   3. Adds an index on (recorded_at DESC) for the "show me the last 13
--      weekly rollups" trend query and (template_id, recorded_at DESC) for
--      per-template trend joins.
--
-- Forward-compatible: when D-3 ships the Outlook Sent Items capture flow,
-- template_sends rows start landing and evaluateTemplateHealth() starts
-- producing non-trivial metrics. The history table catches the inflection
-- point automatically — no manual baseline reset.
-- ============================================================================

BEGIN;

-- ── 1. template_health_history ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.template_health_history (
  id                     bigserial PRIMARY KEY,
  recorded_at            timestamptz NOT NULL DEFAULT now(),
  lookback_days          integer NOT NULL,
  template_count         integer NOT NULL,
  evaluated_count        integer NOT NULL,
  needs_revision_count   integer NOT NULL,
  stale_count            integer NOT NULL,
  total_sends            integer NOT NULL,
  -- Full per-template breakdown so we never have to re-run with old data.
  -- Schema: [{ template_id, name, category, status, total_sends,
  --            avg_edit_dist, open_rate, reply_rate, deal_rate, issues[] }, ...]
  evaluations            jsonb NOT NULL,
  -- Aggregates the cron run wrote into signals + flag tables.
  revisions_flagged      integer NOT NULL DEFAULT 0,
  revision_suggestions   integer NOT NULL DEFAULT 0,
  -- Cron run metadata
  run_source             text NOT NULL DEFAULT 'lcc-template-health-rollup'
                           CHECK (run_source IN ('lcc-template-health-rollup','manual')),
  run_duration_ms        integer,
  notes                  text
);

CREATE INDEX IF NOT EXISTS template_health_history_recorded_idx
  ON public.template_health_history (recorded_at DESC);

CREATE INDEX IF NOT EXISTS template_health_history_needs_revision_idx
  ON public.template_health_history (recorded_at DESC)
  WHERE needs_revision_count > 0;

COMMENT ON TABLE public.template_health_history IS
  'Round 76r2-l1 (2026-05-19): weekly time-series of evaluateTemplateHealth()
   rollups. Populated by pg_cron lcc-template-health-rollup. Read by the
   templates admin UI to render avg-edit-distance / reply-rate / deal-rate
   trend sparklines per template, and by the daily briefing to spot week-
   over-week regressions in template performance.';

-- ── 2. pg_cron schedule ────────────────────────────────────────────────
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
    BEGIN
      PERFORM cron.unschedule('lcc-template-health-rollup');
    EXCEPTION WHEN OTHERS THEN NULL;
    END;

    -- Monday 06:00 UTC — early enough for the morning briefing to read the
    -- fresh rollup, late enough that any Sunday-evening template_sends have
    -- already landed in template_sends.
    PERFORM cron.schedule(
      'lcc-template-health-rollup',
      '0 6 * * 1',
      $cmd$SELECT public.lcc_cron_post(
        '/api/operations?_route=draft&action=health-rollup',
        '{"lookback_days": 120, "persist": true}'::jsonb,
        'vercel'
      )$cmd$
    );
  END IF;
END $$;

COMMIT;
